import { z } from "zod";

export const Caratula = z.object({
  Anno: z.number(),
  DatDecl: z.object({
    NIT: z.number(),
    DV: z.number(),
    PriApell: z.string(),
    SegunApell: z.string(),
    PriNomb: z.string(),
    OtrosNomb: z.string(),
    RazonSoc: z.string(),
    CodDir: z.string(),
  }),
  Tarif: z.object({
    Art240: z.number(),
    Art2401: z.number(),
    Art194240360: z.number(),
    MegaInvHot: z.number(),
    MegaInv: z.number(),
    TarifGen: z.number(),
  }),
  DatosInf: z.object({
    PerNatuSinRes: z.boolean(),
    ContrRegTriEsp: z.boolean(),
    EntCoop: z.boolean(),
    EntSecFin: z.boolean(),
    NueSoc: z.boolean(),
    ObrImp: z.boolean(),
    ProgReorEmp: z.boolean(),
    SocExtPresServ: z.boolean(),
    OblApl: z.boolean(),
    CostInvEstSis: z.boolean(),
    CostInvEstSim: z.boolean(),
    ProgTariImp: z.boolean(),
    ContrEstJur: z.boolean(),
    MonFuncDif: z.boolean(),
    MegInv: z.boolean(),
    EmpEcoNar: z.boolean(),
    CompHoldCol: z.boolean(),
    ZonaEcoSocEsp: z.boolean(),
  }),
  NoIdSig: z.number(),
  CodRepre: z.number(),
  CodCont: z.number(),
  Salvedad: z.boolean(),
  NoTarjProf: z.number(),
});

export const CaratulaInput = {
  "Anno": 0,
  "DatDecl": {
    "NIT": 0,
    "DV": 0,
    "PriApell": "",
    "SegunApell": "",
    "PriNomb": "",
    "OtrosNomb": "",
    "RazonSoc": "",
    "CodDir": ""
  },
  "Tarif": {
    "Art240": 0,
    "Art2401": 0,
    "Art194240360": 0,
    "MegaInvHot": 0,
    "MegaInv": 0,
    "TarifGen": 0
  },
  "DatosInf": {
    "PerNatuSinRes": false,
    "ContrRegTriEsp": false,
    "EntCoop": false,
    "EntSecFin": false,
    "NueSoc": false,
    "ObrImp": false,
    "ProgReorEmp": false,
    "SocExtPresServ": false,
    "OblApl": false,
    "CostInvEstSis": false,
    "CostInvEstSim": false,
    "ProgTariImp": false,
    "ContrEstJur": false,
    "MonFuncDif": false,
    "MegInv": false,
    "EmpEcoNar": false,
    "CompHoldCol": false,
    "ZonaEcoSocEsp": false
  },
  "NoIdSig": 0,
  "CodRepre": 0,
  "CodCont": 0,
  "Salvedad": false,
  "NoTarjProf": 0
}

