const rentaLiquida = {
    Ingresos: {
        IngresosNetosActividadIndustrialCoSer: {
            IngresosNetosActividadIndustrialCoSer: {
                VentaTerritorioNacional: {},
                VentaExportacion: {},
                VentaZonaFranca: {},
                VentaComercializadorasInternacionales: {},
                VentaJurisdiccionesNoCooperantes: {},
                VentaVinculadoEconomicosFranca: {},
                PrestacionServiciosTerritorioNacional: {},
                PrestacionServiciosExportacion: {},
                PrestacionServiciosZonaFranca: {},
                PrestacionServiciosComercializadorasInternacionales: {},
                PrestacionServiciosJurisdiccionesNoCooperantes: {},
                PrestacionServiciosVinculadoEconomicosFranca: {},
                ServiciosConstruccion: {},
                AcuerdosConcesion: {},
                ArrendamientosOperativos: {},
                Regalias: {},
                Comisiones: {},
                HonorariosProfesionales: {},
                ActividadesSegurosCapitalizacion: {},
                LiberacionReservasContratosSeguros: {},
                ComisionesBancarias: {},
                OtrosIngresos: {},
                Total: {},
            },
            DevolucionesRebajasDescuentos: {
                VentaBienes: {},
                PrestacionServicios: {},
                OtrasDevoluciones: {},
                Total: {},
            }
        },
        IngresosFinancieros: {
            ArrendamientoFinanciero: {},
            InteresesSectorFinanciero: {},
            InteresesPrestamosTerceros: {},
            IntrumentosFinancierosMedidos: {},
            InteresesImplicitos: {},
            DiferenciaCambio: {},
            OtrosIngresos: {},
            Total: {},
        },
        GananciasInversionesSubsidiariasAsociadasNegocios: {
            GananciasMetodoParticipacion: {},
            GananciasCambioValorRazonable: {},
            DividendosParticipacionesNoContribuyentes: {},
            DividendosParticipacionesDistribuidosEntidadesNoColombia: {},
            DividendosParticipacionesGravadasTarifaGeneral: {},
            DividendosParticipacionesGravadasPersonaNatural: {},
            DividendosParticipacionesGravadasPersonaNaturalSinResidencia: {},
            DividendosParticipaciones10: {},
            DividendosParticipacionesGravadasTarifaGeneralExtranjeras: {},
            DividendosProyectosMegainversion: {},
            Total: {},
        },
        IngresosPorMedicionesValorRazonable: {
            ActivosBiologicos: {},
            PropiedadesInversion: {},
            InstrumentosFinancieros: {},
            InstrumentosDerivados: {},
            Otros: {},
            Total: {},
        },
        UtilidadVentaEnajenacionActivosMenos2Anos: {
            PropiedadesPlanta: {},
            PropiedadesInversion: {},
            ActivosBiologicos: {},
            ActivosNoCorrientesMantenidosVentaEntregarPropietarios: {},
            ActivosIntangibles: {},
            InversionesAccionesOtrasParticipaciones: {},
            DisposicionOtrosInstrumentosFinancieros: {},
            Otros: {},
            Total: {},
        },
        UtilidadVentaEnajenacionActivosMas2Anos: {
            PropiedadesPlanta: {},
            PropiedadesInversion: {},
            ActivosBiologicos: {},
            ActivosNoCorrientesMantenidosVentaEntregarPropietarios: {},
            ActivosIntangibles: {},
            InversionesAccionesOtrasParticipaciones: {},
            DisposicionOtrosInstrumentosFinancieros: {},
            Otros: {},
            Total: {},
        },
        IngresosReversionDeterioroValor: {
            Inventarios: {},
            PropiedadesPlantaEquipo: {},
            ActivosIntangibles: {},
            ActivosExploracionEvaluacionRecursosMinerales: {},
            PropiedadesInversionMedidasCosto: {},
            ActivosNoCorrientesMantenidosVentaEntregarPropietarios: {},
            ActivosBiologicosMedidosCosto: {},
            BienesArteCultura: {},
            ActivosFinancieros: {},
            CarteraCreditoOperacionesLeasing: {},
            OtrasInversionesMedidasCostoMetodoParticipacion: {},
            OtrosDeterioros: {},
            Total: {},
        },
        IngresosReversionProvisiones: {
            Garantias: {},
            ContratosOnerosos: {},
            Litigios: {},
            ReembolsosClientes: {},
            ReestructuracionesNegocios: {},
            PasivosContingentesCombinacionNegocios: {},
            Otros: {},
            Total: {},
        },
        IngresosReversionPasivosBeneficiosEmpleados:{
            BeneficiosDeCortoPlazo: {},
            BeneficiosDeLargoPlazo: {},
            BeneficiosAEmpeladosPorTerminacionDelVinculoLaboral: {},
            BeneficiosAEmpeladosPostEmpleo: {},
            Total: {},
        },
        OtrosIngresos: {
            TransferenciasSubvencionesAyudasGubernamentales: {},
            DonacionesAportacionesSimilares: {},
            ReembolsosCompaniasSegurosIndemnizaciones: {},
            OtrasIndemnizaciones: {},
            OtrasReversionesRecuperaciones: {},
            Otros: {},
            Total: {},
        },
        GananciasNetasOperacionesDiscontinuas:{},
        AjustesFiscales:{
            AdicionIngresos: {
                RecuperacionDeDeduccionesSinIncidenciaContable: {},
                InteresesPresuntos: {},
                MayorIngresoPreciosDeTransferencia: {},
                OtrosIngresosFiscalesYNoIncluidosContablemente: {},
                Total: {},
            },
            Total: {},
        },
        MenosIngresosNoConstitutivosRenta: {},
        TotalIngresos: {},
    },
    Costos: {
        MateriasPrimasReventaBienes:{
            CostossVentasCalculadoSistemaPermanente: {},
            MateriasPrimasProduccion: {
                InventarioInicial: {},
                ComprasLocales: {},
                Importaciones: {},
                InventarioFinal: {},

            },
            CostoBienesVendidos: {
                InventarioInicial: {},
                ComprasLocales: {},
                Importaciones: {},
                InventarioFinal: {},
            },
            ProductosProceso: {
                InventarioInicial: {},
                InventarioFinal: {},
            },
            ProductosTerminados: {
                InventarioInicial: {},
                InventarioFinal: {},
            },  
            CostosPrestacionServicios: {},
            OtrosSistemasDeterminacionCostoVentas: {},
            Ajustes: {},
            Total: {},
        },
        ManoObra: {
            CortoPlazo: {},
            LargoPlazo: {},
            PostTerminacionVinculoLaboral: {},
            PostEmpleo: {},
            Total: {},
        },
        DepresionacionesAmortizacionesDeterioros:{
            DepreciacionPropiedadesPlantaEquipo: {
                Costo: {},
                AjusteAcumunlado: {},
            },
            DepreciacionPropiedadesInversion: {
                Costo: {},
                AjusteAcumunlado: {},
            },
            DepreciacionActivosBiologicos: {
                Costo: {},
                AjusteAcumunlado: {},
            },
            AmortizacionActivosIntangibles: {
                Costo: {},
                AjusteAcumunlado: {},
            },
            DepreciacionDerechosUsoArrendamientos: {},
            OtrasDepreciacionesAmortizaciones: {
                Costo: {},
                AjusteAcumunlado: {},
            },
            DeterioroValorActivos: {
                Inventarios: {},
                PropiedadesPlantaEquipo: {},
                ActivosIntangibles: {},
                ActivosExploracionEvaluacionRecursosMinerales: {},
                PropiedadesInversionMedidasCosto: {},
                ActivosNoCorrientesMantenidosVentaEntregarPropietarios: {},
                ActivosBiologicosMedidosCosto: {},
                BienesArteCultura: {},
                ActivosFinancieros: {},
                CarteraCreditoOperacionesLeasing: {},
                OtrasInversionesMedidasCostoMetodoParticipacion: {},
                OtrosDeterioros: {},
            },
            Total: {},
        },
        OtrosCostos: {
            Arrendamientos: {},
            Seguros: {},
            Servicios: {},
            Honorarios: {},
            ServiciosTecnicos: {
                VinculadosEconomicos: {},
                JurisdiccionesNoCooperantesBajaNulaImposicion: {},
                NoVinculados: {},
            },
            AsistenciaTecnica: {
                VinculadosEconomicos: {},
                JurisdiccionesNoCooperantesBajaNulaImposicion: {},
                NoVinculados: {},
            },
            OtrosConceptosReconocidosCostos: {},
            OtrosConceptosFiscalesNoReconocidos: {},
            Total: {},
        },
        MenosCostoAjustePrecios: {},
        TotalCostos: {},
    },
    Gastos: {
        Administracion: {
            
        },
    },
}
