export const CalculatedValues = ["SaldFisc", "TotCont", "TotFisc", "REFSaldCont", "REFSaldFisc", "Sub", "ValFin", "Esc1", "Esc2", "Esc3", "Esc4", "ValApli", "Limit", "Desc", "LotRif", "OtroGanOca"];
export const ValuesNames = {
    "SaldCont": "Saldo Contable",
    "Ajust1": "Primer Ajuste",
    "Ajust2": "Segundo Ajuste",
    "Ajust3": "Tercer Ajuste",
    "SaldFisc": "Saldo Fiscal",
    "REFSaldCont": "Saldo Contable",
    "REFSaldFisc": "Saldo Fiscal",
    "TotCont": "Saldo Contable Total",
    "TotFisc": "Saldo Fiscal Total",
    "ValCont": "Valor Contable",
    "ValFisc": "Valor Fiscal",
    "Data": "Datos",
    "Dat": "Datos",
    "Nac": "Moneda Nacional",
    "Ext": "Moneda Extrangera",
    "ValCost": "Valor de adquisición",
    "DetCost": "Deterioro del valor",
    "MedCost": "Medidas al costo",
    "DetCli":"Deterioro sobre clientes y otras cuentas que sí tuvieron en este año o en los anteriores una contrapartida en el ingreso y sin incluir las cuentas por cobrar que sean con vinculados económicos (solo esta provisión, si se ajusta a los máximos permitidos por la norma fiscal, es aceptada fiscalmente; ver art. 145 del ET)",
    "DetDem":"Deterioro sobre las demás cuentas por cobrar (esta sería la que no es aceptada fiscalmente)",
    "MedValRazCamRes": "Medidas al valor razonable con cambios en resultados",
    "MedValRazCamORI": "Medidas al valor razonable con cambios en el ORI",
    "EfectMed": "Efectos por mediciones al valor de mercado",
    "EfectApliPart": "Efectos de aplicación del método de participación",
    "MedMetPart": "Medidas con método de participación",
    "InsFinDervNegMedCost": "Instrumentos financieros derivados con fines de negociación",
    "InsFinDervCovMedCost": "Instrumentos financieros derivados con fines de cobertura",
    "DerFidNegMedCost": "Derechos Fiduciarios",
    "Plus": "Plusvalía o Good will",
    "Adq": "Adquisición de establecimiento de comercio",
    "Fus": "Fusiones",
    "Esci": "Escisiones",
    "CompAcc": "Compra de acciones",
    "DeprAcum": "Depreciación acumulada",
    "DetAcum": "Deterioro acumulado",
    "AniProdCost": "Animales Productores medidos al costo",
    "Reval": "Revaluaciones",
    "AniProdCRaz": "Animales Productores medidos al valor razonable",
    "DetAni": "Deterioro de animales consumibles medidos al costo",
    "AniConsCost": "Animales consumibles medidos al costo",
    "AniConsCRaz": "Animales consumibles medidos al valor razonable",
    "PlaProdCost": "Plantas productoras medidas al costo",
    "PlaProdCRaz": "Plantas productoras medidas al valor razonable",
    "PlaConsCost": "Plantas consumibles medidos al costo",
    "PlaConsCRaz": "Plantas consumibles medidos al valor razonable",
    "Det": "Deterioros",
    "AntiImpRenSobT": "Anticipo del impuesto de renta y de Sobretasa",
    "RetAutFuente": "Retenciones y autorretenciones en la fuente",
    "RetIVA": "Retenciones de IVA",
    "RetICA": "Retenciones de ICA",
    "SaldoFavor": "Saldo a favor renta",
    "SaldoIVA": "Saldos a favor IVA",
    "SaldoICA": "Saldo a favor ICA",
    "CargDifInt":"Cargos diferidos e intangibles que solo son fiscales (ver artículos 32 del ET reglamentado con Decreto 2235 dic 27 de 2017; también los artículos 74, 74-1, 142, 143 y 290 numeral 1 y 3 del eT",
    "AmortAcum": "Amortización acumulada",
    "Plub": "Publicidad",
    "PriSeg": "Primas de seguros",
    "Arrend": "Arrendamientos",
    "Otro": "Otros",
    "Colombia": "En Colombia",
    "NoColombia": "En el exterior",
    "PasivRecFisc": "Pasivos reconocido solamente para fines fiscales (ver por ejemplo el caso del art. 32 del ET y el decreto 2335 de dic.27 de 2017; ver también el art. 289 numeral 2 del ET)",
    "UtilDesImp": "Utilidad después de impuestos",
    "PerDesImp": "Pérdida después de impuestos",
    "GananAcum": "Ganancias acumuladas",
    "PerAcum": "Pérdidas acumuladas",
    "GananAcumORI": "Ganancias acumuladas ORI",
    "PerAcumORI": "Pérdidas acumuladas ORI",
    "MetPar": "Método de participación",
    "CliNac": "A clientes Nacionales por fuera de zona franca (sin importar si son o no Vinculados económicos)",
    "Export": "Exportaciones (sin incluir las exportaciones a territorios o países no cooperantes, anteriormente llamados paraísos fiscales",
    "CliZonFrac": "A clientes en Zonas Francas que no sean vinculados económicos",
    "SocCom": "A sociedades de Comercialización internacional",
    "CliJuri": "A clientes en jurisdicciones no cooperantes (anteriormente llamadas paraísos fiscales; ver decreto 1966 de 2014 recopilado en el artículo 1.2.2.5.1 del DUT 1625 de 2016) pero que no sean vinculados económicos",
    "VincEcoZonFrac": "A vinculados económicos ubicados en Zona Franca o ubicados en cualquier otro país",
    "VentBien": "Venta de bienes",
    "ServGen": "Servicios generales (sin incluir honorarios profesionales)",
    "ServConst": "Servicios de construcción",
    "AcuConcServ": "Acuerdos de concesión de servicios",
    "ArrenOper": "Arrendamientos operativos",
    "Regal": "Regalías",
    "Comis": "Comisiones (relaciones de agencia)",
    "HonProf": "Honorarios Profesionales",
    "ActSegCap": "Actividades de seguros y de capitalización",
    "LibRes": "Liberación de reservas en contratos de seguros",
    "ComBanc": "Comisiones bancarias, costos de transacción, entre otros",
    "ArreFinMerc": "Arrendamiento financiero o mercantil (leasing)",
    "IntFin": "Intereses - sector financiero",
    "IntPrest": "Intereses por préstamos a terceros (diferentes al sector financiero)",
    "IntFinAmrt": "Por instrumentos financieros medidos a costo amortizado distinto a préstamos",
    "IntImplc": "Intereses implícitos (transacciones de financiación)",
    "IntPresSoc": "Intereses presuntivos por hacer préstamos en dinero a los socios de esta sociedad o a otras sociedades donde esta sociedad es socia",
    "RecSocNacMeg": "Recibidos de sociedad nacional del Régimen Ordinario que sí lleva a cabo las Megainversiones del art.235-3 del ET",
    "RecSocNacNoMegNoSoc": "Recibidos de sociedad nacional del Régimen Ordinario que no lleva a cabo las Megainversiones del art.235-3 del ET. y que no está acogida al régimen de sociedades CHC de los arts. 894 a 898 del ET)",
    "RecSocNacNoMegSocR49": "Recibidos de sociedad nacional del Régimen Ordinario que no lleva a cabo las Megainversiones del art.235-3 del ET. pero que sí está acogida al régimen de sociedades CHC de los arts. 894 a 898 del ET, reglamentados con el Decreto 598 de abril 6 de 2020). De acuerdo con el art. 25 literal 'e' del ET, y el art. 895 del ET, si la persona no residente que se lleva estos dividendos no está ubicada en un territorio considerado 'jurisdicción de nula tributación' (antiguos 'paraísos fiscales'; ver listado e art. 1.2.2.5.1 del DUT 1625 de 2018), entonces no tiene ni siquiera que declarar este ingreso como ingreso bruto y luego restarlo como ingreso no gravado pues este ingreso no se considera ingreso de fuente nacional  (es decir, para efectos fiscales no se considera como obtenido en Colombia)",
    "RecSocNacSim": "Recibidos de una sociedad nacional del Régimen Simple (Ver art.. 911 del ET y art.1.2.1.10.7 del DUT 1625 de 2016 sustituido con el Dec.. 1457 de nov de 2020).",
    "RecSocNacNoMegSocR52": "Recibidos de sociedad nacional del Régimen Ordinario que no lleva a cabo las Megainversiones del art.235-3 del ET. pero que sí está acogida al régimen de sociedades CHC de los arts. 894 a 898 del ET, reglamentados con el Decreto 598 de abril 6 de 2020). De acuerdo con el art. 25 literal 'e' del ET, y el art. 895 del ET, si la persona no residente que se lleva estos dividendos no está ubicada en un territorio considerado 'jurisdicción de nula tributación' (antiguos 'paraísos fiscales'; ver listado e art. 1.2.2.5.1 del DUT 1625 de 2018), entonces no tiene que declarar este ingreso pues este ingreso no se considera ingreso de fuente nacional  (es decir, para efectos fiscales no se considera como obtenido en Colombia).",
    "RecSocNacNoMegSocR53": "Recibidos de sociedad nacional del Régimen Ordinario que no lleva a cabo las Megainversiones del art.235-3 del ET. pero que sí está acogida al régimen de sociedades CHC de los arts. 894 a 898 del ET).  De acuerdo con el art. 25 literal 'e' del ET, y el art. 895 del ET, si la persona no residente que se lleva estos dividendos no está ubicada en un territorio considerado 'jurisdicción de nula tributación' (antiguos 'paraísos fiscales'; ver listado e art. 1.2.2.5.1 del DUT 1625 de 2018), entonces no tiene que declarar este ingreso pues este ingreso no se considera ingreso de fuente nacional  (es decir, para efectos fiscales no se considera como obtenido en Colombia).",
    "RecSocNacNoMegSocR54": "Recibidos de sociedad nacional del Régimen Ordinario que no lleva a cabo las Megainversiones del art.235-3 del ET. pero que sí está acogida al régimen de sociedades CHC de los arts. 894 a 898 del ET, reglamentados con el Decreto 598 de abril 6 de 2020). De acuerdo con el art. 25 literal 'e' del ET, y el art. 895 del ET, si la persona no residente que se lleva estos dividendos no está ubicada en un territorio considerado 'jurisdicción de nula tributación' (antiguos 'paraísos fiscales'; ver listado e art. 1.2.2.5.1 del DUT 1625 de 2018), entonces no tiene que declarar este ingreso pues este ingreso no se considera ingreso de fuente nacional  (es decir, para efectos fiscales no se considera como obtenido en Colombia).",
    "PrpPlntEqp": "Propiedades, planta y equipo",
    "PrpInv": "Propiedades de Inversión",
    "ActBio": "Activos biológicos",
    "ActNoCorr": "Activos no corrientes mantenidos para la venta",
    "ActInta": "Activos Intangibles",
    "InvAccOtro": "Inversiones en acciones y otras participaciones",
    "DispInstr": "Por disposición de otros instrumentos financieros",
    "Menos2": "Por ventas de activos poseídos menos de 2 años",
    "Mas2": "Por ventas de activos poseídos más de 2 años",
    "ReembCompSeg": "Reembolsos de compañías de seguros (indemnizaciones)",
    "Inv": "Inventario",
    "ActInt": "Activos intangibles",
    "ActExplrRecMat": "Activos de exploración y evaluación de recursos minerales",
    "ActNoCorrVent": "Activos no corrientes mantenidos para la venta / entregar a propietarios",
    "BienArtCult": "Bienes de arte y cultura",
    "ActFinan": "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)",
    "CartCred": "Cartera de crédito y operaciones de leasing",
    "OtraInv": "Otras inversiones medidas al costo o el método de la participación",
    "Garan": "Garantías",
    "ContOner": "Contratos onerosos",
    "Litig": "Litigios",
    "Reembol": "Reembolsos a clientes",
    "Reestruc": "Reestructuraciones de negocios",
    "Pasiv": "Pasivos contingentes asumidos en una combinación de negocios",
    "BenefCortoPlz": "Beneficios de corto plazo",
    "BenefLargPlz": "Beneficios de largo plazo",
    "BenefEmplTemVinLab": "Beneficios a empleados por terminación del vínculo laboral",
    "BenefEmplPost": "Beneficios a empleados post-empleo",
    "GananApli": "Ganancias por aplicación método de participación",
    "GananCamb": "Ganancias por cambios en el valor razonable de los activos",
    "InvAsoSubNegCon": "Inversiones en asociadas, subsidiarias y negocios conjuntos",
    "PropInv": "Propiedades de inversión",
    "InstFinan": "Instrumentos financieros, diferente a inversiones en subsidiarias, asociadas y/o negocios conjuntos ",
    "InstDer": "Instrumentos derivados",
    "PresServ": "Prestación de servicios",
    "DiviNoGrav": "Dividendos no gravados de un ejercicio 2016 o anteriores, entregados por cualquier tipo de sociedad (ver los valores del renglón 46; ver parágrafo 1 del artículo 1.2.1.10.3 del DUT 1625 de 2016, modificado con el art.2 del Decreto 2371 de dic, de 2019",
    "AprtObl": "Aportes obligatorios a EPS y Fondos de pensiones obligatorias en Colombia (arts. 55 y 56 del ET)",
    "AprtVol": "Aportes voluntarios a fondos de pensiones obligatorias (art. 55 del ET (art. 55 del ET y arts. 1.2.1.12.9, el parágrafo 1 del 1.2.4.1.30 y el 1.2.4.1.41 del DUT 1625 de 2016 luego de ser modificados con los Dec.2250 dic de 2017, 1808 oct de 2019 y 2264 dic. 13 de 2019; no se pueden pasar el 25% del total de ingresos del renglón 53 y al mismo tiempo, en valores absolutos, no se pueden pasar de 2.500 UVT)",
    "UtilEnaj": "Utilidad en la enajenación de acciones  inscritas en bolsa(art. 36-1 del ET)",
    "ValCap": "Por valor capitalizado de la cuenta Revalorización del Patrimonio (ver art.36-3 del ET)",
    "Indem": "Indemnizaciones seguros daño emergente (art. 45 del ET)",
    "Recom": "Recompensas (art. 42 del ET)",
    "Ganan": "Gananciales (art 47 del ET)",
    "SubsAgro": "Subsidios de Agroingreso seguro (art. 57-1 del ET)",
    "InvIniTrbProc": "Inventario inicial de trabajo en proceso",
    "InvIniMatPri": "Inventario inicial de materias primas",
    "CompLoc": "Mas: Compras locales",
    "Imp": "Mas: importaciones",
    "InvFinMatPri": "Menos: Inventario final materias primas",
    "CostManoObr": "Mas: Costo de mano de obra",
    "CortoPlz": "De corto plazo",
    "LargoPlz": "De largo plazo",
    "TermVincLab": "Por terminación del vínculo laboral",
    "PostEmpl": "Post-empleo",
    "CostDepr": "Más: Costos indirectos de fabricación",
    "DeprPrpPltEqu": "Depreciación propiedades, planta y equipo",
    "Cost": "Del costo",
    "AjusAcum": "Del ajuste acumulado por revaluaciones o re expresiones",
    "DeprPrpInv": "Depreciación de propiedades de inversión",
    "DeprActBio": "Depreciación de activos biológicos",
    "DepreActInt": "Amortización de activos intangibles",
    "AmrtGatPagAnti": "Amortización de gastos pagados por anticipado",
    "PrpPltEqu": "Propiedades, planta y equipo",
    "ActExp": "Activos de exploración y evaluación de recursos minerales",
    "PrpInver": "Propiedades de inversión medidas al modelo de costo",
    "BienArt": "Bienes de arte y cultura medidos al modelo de costo",
    "ActFin": "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)",
    "OtrasInv": "Otras inversiones medidas al costo o por el método de la participación",
    "DerUso": "Derechos de uso en arrendamientos operativos (NIIF 16)",
    "Arren": "Arrendamientos",
    "Seguro": "Seguros",
    "Serv": "Servicios",
    "Honor": "Honorarios",
    "ServTecn": "Servicios técnicos",
    "VinEco": "Con Vinculados económicos",
    "JurisNoCoop": "Con Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    "NoVin": "Con No vinculados",
    "InvFinTrbProc": "Menos: Inventario final de trabajo en proceso",
    "InvIniProdTer": "Mas: Inventario inicial de producto terminado",
    "CostFabric": "Mas: Costo de fabricación del periodo",
    "InvFinProdTer": "Menos: Inventario final de producto terminado",
    "CostVentInv": "Costo de ventas para comerciantes que utilizan juego de inventarios",
    "InvIni": "Inventario inicial",
    "Import": "Mas: Importaciones",
    "InvFin": "Menos: Inventario final",
    "CostVenSisPer": "Costo de ventas para comerciantes que utilizan sistema permanente",
    "CostActRenExt": "Costo de las actividades que forman las rentas exentas (costo de prestación del servicio de transporte fluvial de pasajeros)",
    "CostFiscActFij": "Costo fiscal de activos fijos, o biológicos,  vendidos y poseídos menos de dos años",
    "SalOtro": "Salarios y otros",
    "AporEPS": "Aportes a EPS",
    "AporARL": "Aportes a ARL",
    "AporFondPen": "Aportes a fondos de pensiones",
    "AporSENA": "Aportes al SENA",
    "AporICBF": "Aportes al ICBF",
    "AporCajaComp": "Aportes a Cajas de compensación",
    "ServAdmVinEco": "Servicios administrativos-Con vinculados económicos",
    "ServAdmVinTer": "Servicios administrativos-con terceros ubicados en jurisdicciones no cooperantes (paraísos fiscales)",
    "ServAdmNoVin": "Servicios administrativos- con no vinculados",
    "ServTecVinEco": "Asistencia técnica-Con vinculados económicos",
    "ServTecVinTer": "Asistencia técnica-con terceros ubicados en jurisdicciones no cooperantes (paraísos fiscales)",
    "ServTecNoVin": "Asistencia Técnica-con no vinculados",
    "TerJurNoCoop": "Con terceros ubicados en jurisdicciones no cooperantes (paraísos fiscales)",
    "DeprePrpPltEqui": "Depreciación propiedades, planta y equipo",
    "DeprePropInv": "Depreciación de propiedades de inversión",
    "DepreOtro": "Depreciación de Otros activos",
    "AmortActInt": "Amortización de activos intangibles",
    "PrpPltEqui": "Propiedades, planta y equipo",
    "ActExplEva": "Activos de exploración y evaluación de recursos minerales",
    "OtroInv": "Otras inversiones medidas al costo o por el método de la participación",
    "DepreActBio": "Depreciación de activos biológicos",
    "IntDevSectFinan": "Intereses  devengados - sector financiero",
    "IntDevPrestTer": "Intereses devengados por préstamos de terceros (distinto al sector financiero)",
    "InstFin": "Por instrumentos financieros medidos a costo amortizado distinto a préstamos",
    "CstTrans": "Costos de transacción (comisiones bancarias, tasas, entre otros)",
    "DifCamb": "Diferencia en cambio",
    "IntImpl": "Intereses implícitos (transacciones de financiación)",
    "ActProvRecValPres": "Actualización de provisiones reconocidas a valor presente",
    "IntAccPref": "Intereses por acciones preferenciales",
    "OtrosGastFinan": "Otros gastos financieros reconocidos como gasto en el estado de resultados",
    "IntDIANSegSoc": "Intereses de mora DIAN y entidades seguridad social",
    "ActNoCor": "Activos no corrientes mantenidos para la venta / entregar a propietarios",
    "ValorVent": "Valoración y venta de inversiones fondo de liquidez y títulos participativos, entre otros",
    "DispOtroInst": "Por disposición de otros instrumentos financieros",
    "InvAccPart": "Inversiones en acciones y otras participaciones",
    "PerMetPart": "Pérdidas por el método de participación",
    "PerMedValRaz": "Pérdidas por medición a valor razonable",
    "InsFin": "Instrumentos financieros",
    "InsDer": "Instrumentos derivados",
    "Garant": "Garantías",
    "ContOne": "Contratos onerosos",
    "ReembCli": "Reembolsos a clientes",
    "ReestNeg": "Reestructuraciones de negocios",
    "PasivCont": "Pasivos contingentes asumidos en una combinación de negocios",
    "TransBubAyuGub": "Transferencias, subvenciones y ayudas gubernamentales",
    "Don": "Donaciones",
    "DeducEspcPubl": "Deducción por inversión en espectáculos públicos (art. 4 Ley 1493 dic. 2011 y Decreto 1258 jun/12)",
    "DeducInvActFij": "Deducción por inversión en activos fijos productores de renta (art. 158-3 del ET; esto solo lo pueden utilizar quienes hayan alcanzado a incluir ese beneficio en sus contratos de estabilidad jurídica tributaria, Ley 963 de 2005)",
    "IndmnCompAseg": "Indemnizaciones de compañías aseguradoras sobre  activos perdidos en situaciones de fuerza mayor (ver art. 148 del ET))",
    "RecCuen": "Recuperación de cuentas por cobrar que se habían castigado (ver art, .195 del ET)",
    "RecDepre": "Recuperación de la depreciación concedida sobre activos que luego se venden con utilidad (ver art. 190 y 196 del ET; ver este editorial: https://actualicese.com/utilidad-por-venta-de-activo-fijo-depreciable-que-sera-renta-por-recuperacion-de-deducciones/)",
    "CompenPerFisc": "Compensaciones de pérdidas fiscales de años anteriores",
    "Val": "Valor",
    "CompenExcRen": "Compensaciones de excesos de renta presuntiva",
    "Exc": "Valor del exceso del año 2016 de $2.000.000, reajustado fiscalmente con los reajustes del 2017,  2018, 2019, 2020 y 2021; eso sería: 2.000.000 x 1,0407 x 1,0407 x 1,0336 x 1,0390 x 1,0197). . Estos excesos de renta presuntiva sí pueden afectar incluso a las utilidades que arrojen las rentas de trabajo (ver art. 1.2.1.19.16 del DUT 1625 de 2016 luego de ser modificado con el artículo 6 del Decreto 1435 de noviembre 5 de 2020) 2.372.000",
    "Sub": "Subtotal compensaciones que se podrían utilizar (el cual no puede exceder al valor del renglón 72)",
    "ValFin": "Valor final de compensaciones por pérdidas fiscales y por exceso de renta presuntiva sobre liquida que se pueden utilizar",
    "Act235": "Por las actividades del artículo 235-2 del ET (transporte fluvial)",
    "RentNet": "Rentas netas (ingreso menos costos y gastos) obtenidas en Colombia pero que no deben producir impuesto en Colombia pues fueron obtenidas por personas naturales que están residiendo en países con los cuales se están aplicando actualmente algún 'Convenio para evitar la doble tributación internacional' (Ejemplo: Ver Ley 1082 de 2006 con España, o Ley 1261 de 2008 con Chile, etc.)",
    "RentHot": "Rentas hoteleras netas (ingresos menos costos y gastos) obtenidas en hoteles construidos o remodelados entre 2003 y 2017 (ver literal e de parágrafo 5 del artículo 240 del ET)",
    "RentExent": "Renta exenta por regalías de derechos de autor (ver numeral 8 del artículo 235-2 del ET)",
    "PensColom": "Pensiones obtenidas en Colombia (la parte que no exceda de 1.000 UVT mensuales; ver numeral 5 del art. 206 del ET)",
    "ActOmi": "Activos omitidos en años anteriores no revisables por la Dian y que se están incluyendo  en el patrimonio fiscal de esta declaración de renta 2021; ver artículo 239-1 del ET; Recuérdese que los artículos 2 a 6 de la Ley 2155 de septiembre 14 de 2021 concedieron de nuevo la oportunidad de seguir ocultando estos activos al cierre del 2021 y normalizarlos solo durante febrero 28 de 2022 mediante. el formulario especial 445 en el cual se pagaría solo un impuesto del 17% sobre dichos activos; en todo caso el 50% de dicho impuesto se tuvo que haber pagado en calidad de anticipo durante noviembre de 2021; ver Decreto 1340 de octubre de 2021)",
    "PasivNoReal": "Pasivos no reales incluidos en años anteriores no  revisables por la Dian y que se están eliminando  en el patrimonio fiscal de esta declaración de renta 2021; ver artículo 239-1 del ET; Recuérdese que los artículos 2 a 6 de la Ley 2155 de septiembre 14 de 2021 concedieron de nuevo la oportunidad de seguir incluyendo estos pasivos al cierre del 2021 y normalizarlos solo durante febrero de 2022 mediante. el formulario especial 445 en el cual se pagaría solo un impuesto del 17% sobre dichos pasivos; en todo caso el 50% de dicho impuesto se tuvo que haber pagado en calidad de anticipo durante noviembre de 2021; ver Decreto 1340 de octubre de 2021)",
    "RecEsp": "Recuperación especial de deducciones (artículos 195 y 196 del ET)",
    "RentComp": "Renta por comparación patrimonial (solo la calcula la DIAN; art. 236 del ET)",
    "RentLiq": "Renta líquida por Pérdidas compensadas modificadas por Liquidación Oficial; art. 199 del ET)",
    "PreRifLot": "Premios, rifas y loterías",
    "PreVent": "Precio de venta activos fijos poseídos más de dos años",
    "IngHerLeg": "Ingresos por herencias, legados y donaciones",
    "AprtSoc": "Lo recibido por encima del aporte social en los procesos de  liquidación de sociedades o transformación de sociedades donde era socio o accionista y siendo claro que se trata de sociedades que se liquidaron luego de haber existido por más de dos años (art. 301 del ET)",
    "GananOca": "Las demás ganancias ocasionales",
    "ValorQuitCap": "Valores por 'quitas de capital' (condonaciones de deudas) que le hayan hecho al contribuyente acogido a los procesos de reorganización empresarial de la Ley 1116 de 2006 o del Decreto-Ley 560 de abril de 2020",
    "CostFiscAct": "Costo fiscal de activo fijo, o biológico,  vendido y poseído por más de dos años",
    "UtilVent": "Utilidad en venta de acciones inscritas en bolsa y poseídas por más de dos años (art. 36-1 del ET)",
    "HerLegDon": "Un parte de las herencias, legados y donaciones (ver art. 307 del ET) ",
    "Indemn": "Para las indemnizaciones por seguros de vida, solo se puede tomar como exento las primeras 12.500 UVT(unos $453.850.000 en el 2021)",
    "AprtSocEncima": "De la parte recibida por encima del aporte social en los procesos de  liquidación de sociedades  donde era socio o accionista y siendo claro que la sociedad liquidada había existido por más de dos años(art. 301 del ET)",
    "Esc1": "Escenario 1: cuando el valor en la casilla 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020) es igual a cero (0), el valor de las Ganancias ocasionales gravables será el resultado de la siguiente operación: casilla 80 Ingresos por ganancias ocasionales) menos casilla 83 (Costos por ganancias ocasionales) menos casilla 84 (Ganancias ocasionales no gravadas y exentas). En el caso de que el resultado de esta operación sea negativo, el valor de esta casilla será igual a cero (0)",
    "Esc2": "Escenario 2: cuando el valor de la casilla 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020) sea mayor a cero (0) y el valor de la casilla 82 (Utilización pérdidas fiscales acumuladas (inc. 2, art. 15 Decreto 772 de 2020)) es igual a cero (0), el cálculo de las Ganancias ocasionales gravables será el resultado de la siguiente operación: Casilla 80 (Ingresos por ganancias ocasionales) más Casilla 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020) menos Casilla 83 (Costos por ganancias ocasionales) menos casilla 84 (Ganancias ocasionales no gravadas y exentas). Si el resultado es negativo, el valor de esta casilla será igual a cero (0)",
    "Esc3": "Escenario 3: cuando el valor en la Casilla 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020) sea mayor a cero (0), el valor en la casilla 82 (Utilización pérdidas fiscales acumuladas (inc. 2, art. 15 Decreto 772 de 2020) sea mayor a cero (0), y la sumatoria de las casillas 83 (Costos por ganancias ocasionales) y 84 (Ganancias ocasionales no gravadas y exentas) no es mayor al valor de la casilla 80 (Ingresos por ganancias ocasionales), las Ganancias ocasionales gravables serán el resultado de la siguiente operación: Casilla 80 (Ingresos por ganancias ocasionales) más casilla 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020)) menos casilla 82 (Utilización pérdidas fiscales acumuladas (inc. 2, art. 15 Decreto 772 de 2020)) menos casilla 83 (Costos por ganancias ocasionales) menos casilla 84 (Ganancias ocasionales no gravadas y exentas). El valor máximo para diligenciar en la casilla 82 (Utilización pérdidas fiscales acumuladas (inc. 2, art. 15 Decreto 772 de 2020)) debe ser inferior o igual, al menor valor de las casillas 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020) o 32 (Pérdidas fiscales acumuladas años anteriores, sin compensar). ",
    "Esc4": "Escenario 4: cuando el resultado de restar de la casilla 80 (Ingresos por ganancias ocasionales), el valor de la casilla 83 (Costos por ganancias ocasionales) sea negativo, es decir, que se genere una pérdida ocasional, y el valor de la casilla 82 (Utilización pérdidas fiscales acumuladas (inc. 2, art. 15 Decreto 772 de 2020) sea igual a cero (0), bien sea porque en la casilla 32 (Pérdidas fiscales acumuladas años anteriores, sin compensar) no existen pérdidas acumuladas, o de existir el declarante no las desea compensar con las rentas de la casilla 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020), el resultado de las Ganancias ocasionales gravables será el resultado de la siguiente operación: Casilla 80 (Ingresos por ganancias ocasionales) más casilla 81 (Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020) menos casilla 83 (Costos por ganancias ocasionales). Si el resultado es negativo, el valor de esta casilla será igual a cero (0).",
    "DescTrib": "Solo se pueden utilizar los que se mencionan en la versión que hasta diciembre de 2021 tenía el artículo 259-2 del ET, modificado con el artículo 96 de la Ley 2010 de diciembre de 2019. En todo caso, y pese a lo que diga el artículo 259-2 del ET, también se podrá aplicar el nuevo descuento tributario por donaciones al Gobierno nacional para la adquisición de vacunas contra el covid-19, contemplado en el articulo 257-2 del ET, pues fue creado con el artículo 3 de la Ley 2064 de diciembre 9 de 2020, es decir, por una norma posterior a la Ley 2010 de 2019)",
    "DescDonEnt": "Descuento por Donaciones a entidades del régimen especial y a entidades no contribuyentes (Ver arts. 257 y 258 del ET; los artículos 1.2.1.4.1 hasta 1.2.1.4.7 del DUT 1625 de 2016 modificados con art. 1 del Decreto 2150 dic. 20 de 2017; Concepto Unificado 481 de abril de 2018",
    "Donac": "Donación hecha a Fundación",
    "PorcApli": "Porcentaje aplicable",
    "ValApli": "Valor que inicialmente se podría tomar como descuento",
    "Limit": "Límite al cual se debe someter este descuento (no puede exceder del 25% del renglón 92)",
    "Desc": "Valor final que puede tomarse por este descuento",
    "IndCom": "Por industria y comercio y avisos y tableros pagados durante el año (ver art. 115 del ET)",
    "IVA": "Por IVA en compra o construcción de bienes de capital que adquieran o construyan los contribuyentes de renta (sin importar si son o no generadores del IVA en sus ventas, es decir, sin importar sí son o no responsables del IVA; ver art. 258-1 del ET, reglamentado con el Decreto 1089 de agosto 3 de 2020 y afectado con la sentencia de la Corte Constitucional C-379 de septiembre 2 de 2020; ver este editorial https://actualicese.com/descuento-en-renta-por-iva-de-bienes-de-capital-fue-condicionado-por-la-corte-constitucional/",
    "RetTran": "Por retención trasladable en dividendos que primero fueron recibidos por otra sociedad nacional (ver art. 242-1 del ET modificado con art. 50 Ley 2010 de 2019, y los artículos 1.2.4.7.9, 1.2.4.7.10 y 1.2.4.37 del DUT 1625 de 2016 sustituidos  con el art. 4 del Decreto 1457 de noviembre 27 de 2020; ver el siguiente editorial  de noviembre 18 de 2020 https://actualicese.com/tributacion-sobre-dividendos-y-su-respectiva-retencion-volvio-a-ser-reglamentada-parte-i/",
    "OtroDesc":"Otros descuentos que apliquen a los contribuyentes del régimen ordinario pero sin incluir los que son exclusivos de los contribuyentes del régimen simple ( formato 1004 del año gravable 2021; art. 26 Resolución 0098 de octubre de 2020 modificada con la 147 de diciembre 7 de 2021): ver el producto virtual sobre información exógena año gravable 2021: https://actualicese.com/producto/guia-multiformato-novedades-en-la-preparacion-y-presentacion-de-informacion-exogena-tributaria-a-la-dian-por-el-ag-2021/",
    "LotRif": "Sobre loterías rifas y similares",
    "OtroGanOca": "Sobre las demás ganancias ocasionales",
    "Servicio":"Servicios",
    "HonorCom":"Honorarios y comisiones",
    "RenFin":"Rendimientos financieros",
    "DiviPart":"Dividendos y participaciones",
    "Extem": "Por extemporaneidad",
    "510506":"510506-Sueldos","510527":"510527-Auxilio de Transporte","510530":"510530-Cesantías","510533":"510533-Intereses sobre cesantías","510536":"510536-Prima de servicios","510539":"510539-Vacaciones","510548":"510548-Bonificaciones","520506":"520506-Sueldos","520518":"520518-Comisiones","520527":"520527-Auxilio de Transporte","520530":"520530-Cesantías","520533":"520533-Intereses sobre cesantías","520536":"520536-Prima de servicios","520539":"520539-Vacaciones","520548":"520548-Bonificaciones","720506":"720506-Sueldos","720527":"720527-Auxilio de Transporte","720530":"720530-Cesantías","720533":"720533-Intereses sobre cesantías","720536":"720536-Prima de servicios","720539":"720539-Vacaciones","720548":"720548-Bonificaciones",
    "510568":"510568-ARL","510569":"510569-EPS","510570":"510570-Fondos Pensiones","520568":"520568-ARL","520569":"520569-EPS","520570":"520570-Fondos Pensiones","720568":"720568-ARL","720569":"720569-EPS","720570":"720570-Fondos Pensiones",
    "510572":"510572-CAJA COMP","510575":"510575-ICBF","510578":"510578-SENA","520572":"520572-CAJA COMP","520575":"520575-ICBF","520578":"520578-SENA","720572":"720572-CAJA COMP","720575":"720575-ICBF","720578":"720578-SENA",
    "1105":"1105-Caja General","1110":"1110-Bancos","1115":"1115-Remesas en tránsito","1120":"1120-Cuentas de ahorro","1125":"1125-Fondos","1140":"1140-Certificados de depósito a término",
    "1205":"1205-Inversiones en asociadas y subsidiarias-Acciones y aportes en sociedades","1210":"1210-Bonos y otros instrumentos de deuda o patrimonio","1215":"1215-Instrumentos financieros derivados y Derechos Fiduciarios","1216":"1216-Derechos de Recompra de inversiones",
    "1305":"1305-Clientes","1310":"1310-A compañías vinculadas","1315":"1315-Cuenta por cobrar a casa matriz","1320":"1320-Cuentas por cobrar a vinculados económicos","1325":"1325-Cuentas por cobrar a socios o accionistas","1330":"1330-Anticipos y avances","1335":"1335-Depósitos","1340":"1340-Promesas de compraventa","1345":"1345-Ingresos por cobrar","1350":"1350-Retenciones sobre contratos","1360":"1360-Reclamaciones","1365":"1365-Cuentas por cobrar a trabajadores","1380":"1380-Deudores Varios","1399":"1399-Deterioros",
    "1405":"1405-Materias Primas","1410":"1410-Productos en proceso","1415":"1415-Obras de construcción en curso","1430":"1430-Productos terminados","1435":"1435-Mercancías no fabricadas por la empresa","1440":"1440-Bienes raíces para la venta","1455":"1455-Materiales, repuestos y accesorios","1460":"1460-Envases y empaques","1465":"1465-Inventarios en tránsito","1499":"1499-Deterioro de inventarios",
    "1505":"1505-Acuerdos de concesión (modelo del activo intangible) (Ver art. 32 del ET y el Decreto 2235 de diciembre de 2017)","1507":"1507-Activos intangibles exploración y evaluación de recursos minerales","1510":"1510-Marcas, Patentes y licencias","1520":"1520-Otros activos intangibles","1558":"1558-Amortización acumulada","1569":"1569-Deterioro de intangibles","1570":"1570-Plusvalía o Good will","1578":"1578-Amortización acumulada de la plusvalía o Good Will","1579":"1579-Deterioro acumulado de la plusvalía o Good Will",
    "1605":"1605-Animales Productores","1610":"1610-Animales consumibles","1615":"1615-Plantas productoras","1620":"1620-Plantas consumibles",
    "1704":"1704-Terrenos","1708":"1708-Construcciones en curso","1716":"1716-Edificaciones","1720":"1720-Maquinaria y equipo","1724":"1724-Equipo de oficina-Muebles y enseres","1728":"1728-Equipo de comunicación y cómputo","1732":"1732-Equipo médico y científico","1736":"1736-Equipo de hoteles y restaurantes","1740":"1740-Flota y equipo de transporte","1745":"1745-Bienes recibidos en Leasing","1768":"1768-Depreciación acumulada","1769":"1769-Deterioro","1779":"1779-Propiedades de inversión-Terrenos","1780":"1780-Propiedades de inversión-Edificaciones","1788":"1788-Prop. De inversi.-Depreciación acumulada-","1789":"1789-Propie.de Invers-Deterio acumulado","1790":"1790-Activos no corrienes mantenidos para la venta",
    "1805":"1805-Anticipos por impuestos corrienes","1810":"1810-Gastos pagados por anticipado","1850":"1850-Otros activos","1860":"1860-Activo por impuesto diferido (ver anexo en el formato 2516)",
    "2105":"2105-Bancos Nacionales","2110":"2110-Bancos del exterior","2115":"2115-Corporaciones financieras","2205":"2205-Proveedores-Nacionales","2210":"2210-Proveedores-Exterior","2335":"2335-Costos y gastos por pagar","2355":"2355-Deudas con sociedades donde se es socio o accionista","2365":"2365-Retención en la fuente","2367":"2367-Retención de IVA","2368":"2368-Retención de Industria y comercio","2370":"2370-Retenciones y aportes en nómina","2404":"2404-Impuesto por pagar - De renta y complementarios","2408":"2408-Impuestos sobre las ventas","2412":"2412-Otros impuestos por pagar","2505":"2505-Salarios por pagar","2510":"2510-Cesantías Consolidadas","2515":"2515-Interés de Cesantías","2525":"2525-Vacaciones Consolidadas","2530":"2530-Prestaciones extralegales","2605":"2605-Provisión - Para costos y gastos","2705":"2705-Ingresos recibidos por anticipado","2710":"2710-Abonos diferidos","2715":"2715-Utilidad diferida en ventas a plazos","2805":"2805-Anticipos y avances recibidos","2810":"2810-Depósitos recibidos","2815":"2815-Ingresos recibidos para terceros","2816":"2816-Pasivo por ingreso diferido (ingresos facturados de forma anticipada; ver anexo de 'ingresos y facturación' en el formato 2516)","2820":"2820-Cuentas de operación conjunta","2825":"2825-Retenciones a terceros sobre contratos","2826":"2826-Pasivo por impuesto diferido (ver anexo en el formato 2516)","2835":"2835-Acreedores del sistema","2840":"2840-Cuentas en participación","2895":"2895-Diversos",
    "3130":"3130-Capital de personas naturales","3605":"3605-Resultado del ejercicio","3705":"3705-Utilidades de periodos anteriores","3710":"3710-Pérdidas de ejercicios anteriores","3715":"3715-Ganancias (pérdidas) acumuladas o retenidas por la adopción por primera","3720":"3720-Otro resultado integral Acumulado","3805":"3805-Superávit",
    "421005":"421005-Financieros - intereses","421020":"421020-Diferencia en cambio","421021":"421021-Otros ingresos financieros",
    "4245":"4245-Utilidad en venta de activo fijo","4265":"4265-Ingresos de ejercicios anteriores","425035":"425035-Reversión de deterioro de valor","425036":"425036-Reversión de provisiones (pasivos de monto o fecha inciertos)","425037":"425037-Reversión de pasivos por beneficios a los empleados","425050":"425050-Reintegro de otros costos y gastos","4255":"4255-Indemnizaciones","4295":"4295-Diversos","429501":"429501-Ganancias por aplicación método de participación","429502":"429502-Transferencias, subvenciones y ayudas gubernamentales","429503":"429503-Donaciones, aportaciones y similares","429506":"429506-Otras reversiones o recuperaciones","429507":"429507-Otros","429543":"429543-Loterías rifas y similares",
    "4175":"4175-Devoluciones y rebajas en ventas",
    "61":"61-Costos de las mercancías fabricadas y vendidas","6140":"6140-Costo de las actividades que forman las rentas exentas (costo de prestación del servicio de transporte fluvial de pasajeros)",
    "5105":"5105-Beneficios a empleados-de corto plazo","5110":"5110, 5135-Honorarios","5115":"5115-Impuestos (al patrimonio, industria y comercio, etc.)","5120":"5120-Arrendamientos","5125":"5125-Contribuciones","5130":"5130-Seguros","5135":"5135-Servicios","5136":"5136-Regalías","5137":"5137-Gastos de investigación","5140":"5140-Gastos Legales","5145":"5145-Mantenimiento y reparación","5150":"5150-Adecuaciones e instalaciones","5155":"5155-Gastos de transportes","5160":"5160-Depreciaciones","5165":"5165-Amortización de gastos pagados por anticipado","5166":"5166-Amortización de activos intangibles","5195":"5195-Diversos","5199":"5199-Deterioros",
    "5205":"5205-Beneficios a los empleados-Corto plazo","5210":"5210-Honorarios","5215":"5215-Impuestos (al patrimonio, industria y comercio, etc.)","521501":"521501-IVA en la adquisición o importación de bienes de capital mediante leasing (ver art. 115-2) del ET","5220":"5220-Arrendamientos","5225":"5225-Contribuciones","5230":"5230-Seguros","5235":"5235-Servicios","5236":"5236-Regalías","5237":"5237-Constitución de reservas (empresas aseguradoras)","5238":"5238-Liquidación de siniestros","5239":"5239-Primas de reaseguros","5240":"5240-Gastos Legales","5241":"5241-Investigación y desarrollo","5245":"5245-Mantenimiento y reparación","5250":"5250-Adecuaciones e instalaciones","5255":"5255-Gastos de transportes","5260":"5260-Depreciaciones","5265":"5265-Amortización de gastos pagados por anticipado","5266":"5266-Amortización de activos intangibles","5295":"5295-Diversos","5299":"5299-Deterioros",
    "5305":"5305-Intereses devengados - sector financiero",
    "5310":"5310-Pérdida en venta y retiro de bienes poseídos menos de dos años","5313":"5313-Pérdida por inversiones en subsidiarias, asociadas y/o negocios conjuntos","5314":"5314-Pérdidas por mediciones a valor razonable","5315":"5315-Gastos por provisiones (pasivos de monto o fecha inciertos)","5316":"5316-Gastos extraordinarios","5395":"5395-Gastos diversos",
    
};
export const TabsNames = {
    "R33": "Renglón 33: Total Costos y Gastos De Nómina",
    "R34": "Renglón 34: Aportes al Sistema de Seguridad Social",
    "R35": "Renglón 35: Aportes al Sena, ICBF, Caja Compensación",
    "R36": "Renglón 36: Efectivo y equivalentes de efectivo",
    "R37": "Renglón 37: Inversiones e instrumentos financieros derivados",
    "R38": "Renglón 38: Cuentas, documentos y arrendamientos financieros por cobrar",
    "R39": "Renglón 39: Inventarios",
    "R40": "Renglón 40: Activos intangibles",
    "R41": "Renglón 41: Activos biológicos",
    "R42": "Renglón 42: Propiedades, planta y Equipo, propiedades de inversión y ANCMV",
    "R43": "Renglón 43: Otros Activos",
    "R44": "Renglón 44: Total patrimonio bruto (sume 36 a 43)",
    "R45": "Renglón 45: Pasivos",
    "R46": "Renglón 46: Total patrimonio líquido-positivo (44-45)",
    "R47": "Renglón 47: Ingresos brutos de actividades ordinarias",
    "R48": "Renglón 48: Ingresos financieros",
    "R49": "Renglón 49: Dividendos y/o participaciones no constitutivos de renta ni ganancia ocasional",
    "R50": "Renglón 50: Dividendos y/o participaciones distribuidos por entidades no residentes en Colombia a una CHC y prima en colocación de acciones",
    "R51": "Renglón 51: Dividendos y/o participaciones gravadas, años 2016 y anteriores, recibidos por sociedades extranjeras",
    "R52": "Renglón 52: Dividendos y/o participaciones gravadas, años 2016 y anteriores, recibidos por personas naturales sin residencia fiscal",
    "R53": "Renglón 53: Dividendos y/o participaciones gravadas, años 2017 y siguientes, recibidos por personas naturales sin residencia fiscal",
    "R54": "Renglón 54: Dividendos y/o participaciones no gravadas, años 2017 y siguientes, pero que tributarán al 10 %",
    "R55": "Renglón 55: Dividendos y/o participaciones gravadas, años 2017 y siguientes, recibidos por establecimientos permanentes y por sociedades extranjeras , excepto las que se reportan en el renglón 56 (ver artículo 245 del ET)",
    "R56": "Renglón 56: Dividendos y participaciones gravados, años 2017 y siguientes, recibidos de parte de una sociedad que llevó a cabo megainversiones, y que fueron recibidos por sociedades nacionales, o por sociedades extranjeras, o por personas naturales no residentes (tributan al 27 %)",
    "R57": "Renglón 57: Otros ingresos",
    "R58": "Renglón 58: Total Ingresos Brutos (sume 47 a 57)",
    "R59": "Renglón 59: Menos: Devoluciones, descuentos y rebajas",
    "R60": "Renglón 60: Ingresos no constitutivos de renta ni ganancia ocasional",
    "R61": "Renglón 61: Total ingresos netos (58-59-60)",
    "R62": "Renglón 62: Costos",
    "R63": "Renglón 63: Gastos de administración",
    "R64": "Renglón 64: Gastos de distribución y ventas",
    "R65": "Renglón 65: Gastos financieros",
    "R66": "Renglón 66: Otros gastos y deducciones",
    "R67": "Renglón 67: Total costos y gastos deducibles (suma 62 a 66)",
    "R68": "Renglón 68: Inversiones efectuadas en el año (ESAL RTE)",
    "R69": "Renglón 69: Inversiones liquidadas de periodos gravables anteriores (ESAL RTE)",
    "R70": "Renglón 70: Renta por recuperación de deducciones",
    "R71": "Renglón 71: Renta líquida pasiva-Entidades controladas del Exterior sin residencia fiscal en Colombia (ECE) (ver arts. 882 a 893 del ET y el concepto Unificado DIAN 9193 de abril 10 de 2018)",
    "R72": "Renglón 72: Renta líquida ordinaria del ejercicio sin casillas 52 a 56 (si 61+ 69 + 70 + 71 - 52 - 53 - 54 - 55 - 56 - 67 - 68 mayor a cero)",
    "R73": "Renglón 73: Pérdida líquida del ejercicio sin casillas 52 a 56 ( si 52 + 53 + 54 + 55 + 56 + 67 + 68 - 61 - 69 - 70 - 71 mayor a cero) (*-39)",
    "R74": "Renglón 74: Compensaciones (*-39)",
    "R75": "Renglón 75: Renta líquida sin casillas 52 a 56 (72-74)",
    "R76": "Renglón 76: Renta presuntiva",
    "R77": "Renglón 77: Rentas exentas",
    "R78": "Renglón 78: Rentas gravables",
    "R79": "Renglón 79: Renta líquida gravada sin casillas 52 a 56 (al mayor valor entre 75 y 76 reste 77 y sume 78)",
    "R80": "Renglón 80: Ingresos por ganancias ocasionales",
    "R81": "Renglón 81: Rentas deudores régimen Ley 1116 de 2006, Decreto-Ley 560 de abril 15 de 2020 y artículo 15 Decreto-Ley 772 de junio 3 de 2020",
    "R82": "Renglón 82: Utilización pérdidas fiscales acumuladas (inciso 2, artículo 15 Decreto 772 de 2020)",
    "R83": "Renglón 83: Costos y deducciones por ganancias ocasionales",
    "R84": "Renglón 84: Ganancias ocasionales no gravadas y exentas",
    "R85": "Renglón 85: Ganancias ocasionales gravables (se calcula conforme a 4 escenarios posibles; ver instructivo)",
    "R86": "Renglón 86: Impuesto sobre la renta líquida gravable sin casillas 52 a 56 (base renglón 79; ver art. 247 del ET; 35%)",
    "R87": "Renglón 87: De dividendos y/o participaciones gravadas a la tarifa del 10 % (base casilla 54) (ver art. 245 y 246-1 del ET)",
    "R88": "Renglón 88: De dividendos y/o participaciones gravadas a la tarifa del artículo 240 del ET (base casilla 55)",
    "R89": "Renglón 89: De dividendos y/o participaciones gravadas a la tarifa del 27 % (base casilla 56)",
    "R90": "Renglón 90: De dividendos y/o participaciones gravadas a la tarifa  del art. 240 (31%+10% del 69%; ver art. 245 del ET) (base casilla 53)",
    "R91": "Renglón 91: Impuesto de dividendos y/o participaciones gravadas a la tarifa del 33% (base casilla 52)",
    "R92": "Renglón 92: Total impuesto sobre las rentas líquidas gravables (suma 86 a 91)",
    "R93": "Renglón 93: Descuentos Tributarios",
    "R94": "Renglón 94: Impuesto neto de renta (92-93)",
    "R95": "Renglón 95: Impuesto de ganancias ocasionales",
    "R96": "Renglón 96: Descuentos por impuestos pagados en el exterior por ganancias ocasionales",
    "R97": "Renglón 97: Total impuesto a cargo (94+95-96)",
    "R98": "Renglón 98: Valor inversión obras por impuestos hasta del 50% del valor de la casilla 88 (Modalidad de pago 1)",
    "R99": "Renglón 99: Descuento efectivo inversión obras por impuestos (modalidad de pago 2)",
    "R100": "Renglón 100: Crédito fiscal artículo 256-1 ET",
    "R101": "Renglón 101: Menos: Anticipo renta liquidado año gravable anterior",
    "R102": "Renglón 102: Menos: Saldo a favor renta  sin solicitud de devolución ni compensación",
    "R103": "Renglón 103: Autorretenciones",
    "R104": "Renglón 104: Otras retenciones",
    "R105": "Renglón 105: Total retenciones año gravable a declarar(103+104)",
    "R106": "Renglón 106: Más: Anticipo renta para el año gravable siguiente (ver anexo)",
    "R107": "Renglón 107: Menos: Anticipo sobretasa instituciones financieras año gravable anterior",
    "R108": "Renglón 108: Más: Sobretasa instituciones financieras",
    "R109": "Renglón 109: Más: Anticipo sobretasa instituciones financieras año gravable siguiente",
    "R110": "Renglón 110: Saldo a pagar por impuesto (si 97 + 106 + 108 + 109 - 98 - 99 - 100 - 101 - 102 -105 - 107 mayor a cero ; si el resultado es negativo escriba 0)",
    "R111": "Renglón 111: Sanciones",
    "R112": "Renglón 112: Total saldo a pagar (si 97 + 106 + 108 +109 + 111 - 98 - 99 - 100 - 101 - 102 - 105 - 107 mayor a cero; si el resultado es negativo escriba 0)",
    "R113": "Renglón 113: Total saldo a favor (si 98 + 99 +100 + 101+ 102 +105 + 107 - 97 - 106 - 108 - 109 - 111; si el resultado es negativo escriba 0)",
    "R114": "Renglón 114: Valor total impuesto exigible por obras por impuestos modalidad de pago 1",
    "R115": "Renglón 115: Valor total proyecto obras por impuestos modalidad de pago 2"
};
export const RSumNorm = ["R33", "R34", "R35", "R36", "R37", "R38", "R39", "R40", "R41", "R42", "R43", "R45", "R47", "R48", "R49", "R52", "R53",
    "R54", "R56", "R57", "R59", "R62", "R63", "R64", "R65", "R66", "R70", "R81", "R83"
];

export const RSumFisc = ["R60", "R84"];

export const RSumVal = ["R77", "R78", "R82", "R95"];

export const addRetencion = {
    "Nombre": "",
    "Nit": "",
    "SaldCont": 0,
    "Ajust1": 0,
    "Ajust2": "",
    "Ajust3": 0,
    "SaldFisc": 0
}
