export const CalculatedValues = ["Activos.ActivosEquivalentesEfectivo.Total.ValorContable",
    "Activos.ActivosEquivalentesEfectivo.Total.EfectoConversion",
    "Activos.ActivosEquivalentesEfectivo.Total.MenorValorFiscal",
    "Activos.ActivosEquivalentesEfectivo.Total.MayorValorFiscal",
    "Activos.ActivosEquivalentesEfectivo.Total.ValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.InversionesInstrumentosFinancierosDerivados.Total.ValorContable",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.InversionesInstrumentosFinancierosDerivados.Total.EfectoConversion",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.InversionesInstrumentosFinancierosDerivados.Total.MenorValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.InversionesInstrumentosFinancierosDerivados.Total.MayorValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.InversionesInstrumentosFinancierosDerivados.Total.ValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.DeterioroAcumuladoInversiones.Total.ValorContable",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.DeterioroAcumuladoInversiones.Total.EfectoConversion",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.DeterioroAcumuladoInversiones.Total.MenorValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.DeterioroAcumuladoInversiones.Total.MayorValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.DeterioroAcumuladoInversiones.Total.ValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.Total.EfectoConversion",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.Total.ValorContable",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.Total.MenorValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.Total.MayorValorFiscal",
    "Activos.InversionesInstrumentosFinancierosDerivadosVN.Total.ValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.CuentasDocumentosPorCobrar.Total.EfectoConversion",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.CuentasDocumentosPorCobrar.Total.ValorContable",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.CuentasDocumentosPorCobrar.Total.MenorValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.CuentasDocumentosPorCobrar.Total.MayorValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.CuentasDocumentosPorCobrar.Total.ValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.DeterioroAcumuladoValorCuentasDocumentosCobrar.Total.EfectoConversion",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.DeterioroAcumuladoValorCuentasDocumentosCobrar.Total.ValorContable",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.DeterioroAcumuladoValorCuentasDocumentosCobrar.Total.MenorValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.DeterioroAcumuladoValorCuentasDocumentosCobrar.Total.MayorValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.DeterioroAcumuladoValorCuentasDocumentosCobrar.Total.ValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.Total.EfectoConversion",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.Total.ValorContable",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.Total.MenorValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.Total.MayorValorFiscal",
    "Activos.CuentasComercialesCobrarOtrasPorCobrar.Total.ValorFiscal",
    "Activos.Inventarios.Total.ValorContable",
    "Activos.Inventarios.Total.EfectoConversion",
    "Activos.Inventarios.Total.MenorValorFiscal",
    "Activos.Inventarios.Total.MayorValorFiscal",
    "Activos.Inventarios.Total.ValorFiscal",
    "Activos.GastosPagadosPorAnticipado.Total.ValorContable",
    "Activos.GastosPagadosPorAnticipado.Total.EfectoConversion",
    "Activos.GastosPagadosPorAnticipado.Total.MenorValorFiscal",
    "Activos.GastosPagadosPorAnticipado.Total.MayorValorFiscal",
    "Activos.GastosPagadosPorAnticipado.Total.ValorFiscal",
    "Activos.ActivosImpuestosCorrientes.Total.ValorContable",
    "Activos.ActivosImpuestosCorrientes.Total.EfectoConversion",
    "Activos.ActivosImpuestosCorrientes.Total.MenorValorFiscal",
    "Activos.ActivosImpuestosCorrientes.Total.MayorValorFiscal",
    "Activos.ActivosImpuestosCorrientes.Total.ValorFiscal",
    "Activos.ActivosImpuestosDiferidos.ValorContable",
    "Activos.ActivosImpuestosDiferidos.EfectoConversion",
    "Activos.ActivosImpuestosDiferidos.MenorValorFiscal",
    "Activos.PropiedadesPlantaEquipo.Total.ValorContable",
    "Activos.PropiedadesPlantaEquipo.Total.EfectoConversion",
    "Activos.PropiedadesPlantaEquipo.Total.MenorValorFiscal",
    "Activos.PropiedadesPlantaEquipo.Total.MayorValorFiscal",
    "Activos.PropiedadesPlantaEquipo.Total.ValorFiscal",
    "Activos.ActivosIntangibles.ActivosIntangiblesDistintosPlusvalia.Total.ValorContable",
    "Activos.ActivosIntangibles.ActivosIntangiblesDistintosPlusvalia.Total.EfectoConversion",
    "Activos.ActivosIntangibles.ActivosIntangiblesDistintosPlusvalia.Total.MenorValorFiscal",
    "Activos.ActivosIntangibles.ActivosIntangiblesDistintosPlusvalia.Total.MayorValorFiscal",
    "Activos.ActivosIntangibles.ActivosIntangiblesDistintosPlusvalia.Total.ValorFiscal",
    "Activos.ActivosIntangibles.PlusvaliaGoodwill.Total.ValorContable",
    "Activos.ActivosIntangibles.PlusvaliaGoodwill.Total.EfectoConversion",
    "Activos.ActivosIntangibles.PlusvaliaGoodwill.Total.MenorValorFiscal",
    "Activos.ActivosIntangibles.PlusvaliaGoodwill.Total.MayorValorFiscal",
    "Activos.ActivosIntangibles.PlusvaliaGoodwill.Total.ValorFiscal",
    "Activos.ActivosIntangibles.Total.ValorContable",
    "Activos.ActivosIntangibles.Total.EfectoConversion",
    "Activos.ActivosIntangibles.Total.MenorValorFiscal",
    "Activos.ActivosIntangibles.Total.MayorValorFiscal",
    "Activos.ActivosIntangibles.Total.ValorFiscal",
    "Activos.PropiedadesInversion.Total.ValorContable",
    "Activos.PropiedadesInversion.Total.EfectoConversion",
    "Activos.PropiedadesInversion.Total.MenorValorFiscal",
    "Activos.PropiedadesInversion.Total.MayorValorFiscal",
    "Activos.PropiedadesInversion.Total.ValorFiscal",
    "Activos.ActivosNoCorrientes.Total.ValorContable",
    "Activos.ActivosNoCorrientes.Total.EfectoConversion",
    "Activos.ActivosNoCorrientes.Total.MenorValorFiscal",
    "Activos.ActivosNoCorrientes.Total.MayorValorFiscal",
    "Activos.ActivosNoCorrientes.Total.ValorFiscal",
    "Activos.ActivosBiologicos.AnimalesVivos.Total.ValorContable",
    "Activos.ActivosBiologicos.AnimalesVivos.Total.EfectoConversion",
    "Activos.ActivosBiologicos.AnimalesVivos.Total.MenorValorFiscal",
    "Activos.ActivosBiologicos.AnimalesVivos.Total.MayorValorFiscal",
    "Activos.ActivosBiologicos.AnimalesVivos.Total.ValorFiscal",
    "Activos.ActivosBiologicos.PlantasProductorasCultivosConsumibles.Total.ValorContable",
    "Activos.ActivosBiologicos.PlantasProductorasCultivosConsumibles.Total.EfectoConversion",
    "Activos.ActivosBiologicos.PlantasProductorasCultivosConsumibles.Total.MenorValorFiscal",
    "Activos.ActivosBiologicos.PlantasProductorasCultivosConsumibles.Total.MayorValorFiscal",
    "Activos.ActivosBiologicos.PlantasProductorasCultivosConsumibles.Total.ValorFiscal",
    "Activos.ActivosBiologicos.Total.ValorContable",
    "Activos.ActivosBiologicos.Total.EfectoConversion",
    "Activos.ActivosBiologicos.Total.MenorValorFiscal",
    "Activos.ActivosBiologicos.Total.MayorValorFiscal",
    "Activos.ActivosBiologicos.Total.ValorFiscal",
    "Activos.OtrosActivos.Total.ValorContable",
    "Activos.OtrosActivos.Total.EfectoConversion",
    "Activos.OtrosActivos.Total.MenorValorFiscal",
    "Activos.OtrosActivos.Total.MayorValorFiscal",
    "Activos.OtrosActivos.Total.ValorFiscal",
    "Pasivos.ObligacionesFinancierasCuentasPorPagar.Total.ValorContable",
    "Pasivos.ObligacionesFinancierasCuentasPorPagar.Total.EfectoConversion",
    "Pasivos.ObligacionesFinancierasCuentasPorPagar.Total.MenorValorFiscal",
    "Pasivos.ObligacionesFinancierasCuentasPorPagar.Total.MayorValorFiscal",
    "Pasivos.ObligacionesFinancierasCuentasPorPagar.Total.ValorFiscal",
    "Pasivos.ArrendamientosPorPagar.Total.ValorContable",
    "Pasivos.ArrendamientosPorPagar.Total.EfectoConversion",
    "Pasivos.ArrendamientosPorPagar.Total.MenorValorFiscal",
    "Pasivos.ArrendamientosPorPagar.Total.MayorValorFiscal",
    "Pasivos.ArrendamientosPorPagar.Total.ValorFiscal",
    "Pasivos.OtrosPasivosFinancieros.Total.ValorContable",
    "Pasivos.OtrosPasivosFinancieros.Total.EfectoConversion",
    "Pasivos.OtrosPasivosFinancieros.Total.MenorValorFiscal",
    "Pasivos.OtrosPasivosFinancieros.Total.MayorValorFiscal",
    "Pasivos.OtrosPasivosFinancieros.Total.ValorFiscal",
    "Pasivos.ImpuestosGravamenesTasasPorPagar.ValorContable",
    "Pasivos.ImpuestosGravamenesTasasPorPagar.EfectoConversion",
    "Pasivos.ImpuestosGravamenesTasasPorPagar.MenorValorFiscal",
    "Pasivos.ImpuestosGravamenesTasasPorPagar.MayorValorFiscal",
    "Pasivos.ImpuestosGravamenesTasasPorPagar.ValorFiscal",
    "Pasivos.PasivosImpuestosDiferidos.ValorContable",
    "Pasivos.PasivosImpuestosDiferidos.EfectoConversion",
    "Pasivos.PasivosImpuestosDiferidos.MenorValorFiscal",
    "Pasivos.PasivosBeneficiosEmpleados.Total.ValorContable",
    "Pasivos.PasivosBeneficiosEmpleados.Total.EfectoConversion",
    "Pasivos.PasivosBeneficiosEmpleados.Total.MenorValorFiscal",
    "Pasivos.PasivosBeneficiosEmpleados.Total.MayorValorFiscal",
    "Pasivos.PasivosBeneficiosEmpleados.Total.ValorFiscal",
    "Pasivos.Provisiones.Total.ValorContable",
    "Pasivos.Provisiones.Total.EfectoConversion",
    "Pasivos.Provisiones.Total.MenorValorFiscal",
    "Pasivos.Provisiones.Total.MayorValorFiscal",
    "Pasivos.Provisiones.Total.ValorFiscal",
    "Pasivos.PasivosIngresosDiferidos.Total.ValorContable",
    "Pasivos.PasivosIngresosDiferidos.Total.EfectoConversion",
    "Pasivos.PasivosIngresosDiferidos.Total.MenorValorFiscal",
    "Pasivos.PasivosIngresosDiferidos.Total.MayorValorFiscal",
    "Pasivos.PasivosIngresosDiferidos.Total.ValorFiscal",
    "Pasivos.OtrosPasivos.Total.ValorContable",
    "Pasivos.OtrosPasivos.Total.EfectoConversion",
    "Pasivos.OtrosPasivos.Total.MenorValorFiscal",
    "Pasivos.OtrosPasivos.Total.MayorValorFiscal",
    "Pasivos.OtrosPasivos.Total.ValorFiscal",
    "TotalPatrimonio.ValorContable",
    "TotalPatrimonio.EfectoConversion",
    "TotalPatrimonio.MenorValorFiscal",
    "TotalPatrimonio.MayorValorFiscal",
    "TotalPatrimonio.ValorFiscal",
    "Activos.Total.ValorContable",
    "Activos.Total.EfectoConversion",
    "Activos.Total.MenorValorFiscal",
    "Activos.Total.MayorValorFiscal",
    "Activos.Total.ValorFiscal",
    "Pasivos.Total.ValorContable",
    "Pasivos.Total.EfectoConversion",
    "Pasivos.Total.MenorValorFiscal",
    "Pasivos.Total.MayorValorFiscal",
    "Pasivos.Total.ValorFiscal",
    "PatrimonioContable.CapitalSocialReservas.Total.ValorContable",
    "PatrimonioContable.CapitalSocialReservas.Total.EfectoConversion",
    "PatrimonioContable.ResultadoEjercicio.Total.ValorContable",
    "PatrimonioContable.ResultadoEjercicio.Total.EfectoConversion",
    "PatrimonioContable.ResultadosAcumulados.Total.ValorContable",
    "PatrimonioContable.ResultadosAcumulados.Total.EfectoConversion",
    "PatrimonioContable.GananciasPerdidasAcumuladasRetenidasAdopcionPrimera.Total.ValorContable",
    "PatrimonioContable.GananciasPerdidasAcumuladasRetenidasAdopcionPrimera.Total.EfectoConversion",
    "PatrimonioContable.OtroResultadoIntegralAcumulado.Total.ValorContable",
    "PatrimonioContable.OtroResultadoIntegralAcumulado.Total.EfectoConversion",
    "PatrimonioContable.Total.ValorContable",
    "PatrimonioContable.Total.EfectoConversion",
    "DatosInformativos.Activos.TotalIntereses.ValorContable",
    "DatosInformativos.Activos.TotalIntereses.EfectoConversion",
    "DatosInformativos.Activos.TotalActivos.ValorContable",
    "DatosInformativos.Activos.TotalActivos.EfectoConversion",
    "DatosInformativos.Activos.TotalActivos.ValorFiscal",
    "DatosInformativos.Activos.InventariosTerceros.ValorContable",
    "DatosInformativos.Activos.InventariosTerceros.EfectoConversion",
    "DatosInformativos.Activos.InventariosPoderTerceros.ValorContable",
    "DatosInformativos.Activos.InventariosPoderTerceros.EfectoConversion",
    "DatosInformativos.Pasivos.TotalInteresespasivos.ValorContable",
    "DatosInformativos.Pasivos.TotalInteresespasivos.EfectoConversion",
    "DatosInformativos.Pasivos.TotalPasivos.ValorContable",
    "DatosInformativos.Pasivos.TotalPasivos.EfectoConversion",
    "DatosInformativos.Pasivos.TotalPasivos.ValorFiscal",
    "DatosInformativos.RetencionFuenteTrasladableArt2421ET.ValorContable",
    "DatosInformativos.RetencionFuenteTrasladableArt2421ET.EfectoConversion",
    "DatosInformativos.Patrimonio.DividendosGravadosDecretadosPeriodo.ValorContable",
    "DatosInformativos.Patrimonio.DividendosGravadosDecretadosPeriodo.EfectoConversion",
    "DatosInformativos.Patrimonio.DividendosNoGravadosDecretadosPeriodo.ValorContable",
    "DatosInformativos.Patrimonio.DividendosNoGravadosDecretadosPeriodo.EfectoConversion",
    "DatosInformativos.Patrimonio.DividendosGravadosPagadosPeriodo.ValorContable",
    "DatosInformativos.Patrimonio.DividendosGravadosPagadosPeriodo.EfectoConversion",
    "DatosInformativos.Patrimonio.DividendosNoGravadosPagadosPeriodo.ValorContable",
    "DatosInformativos.Patrimonio.DividendosNoGravadosPagadosPeriodo.EfectoConversion",
    "DatosInformativos.Patrimonio.DividendosGravadosPagadosPeriodoCargoUtilidades.ValorContable",
    "DatosInformativos.Patrimonio.DividendosGravadosPagadosPeriodoCargoUtilidades.EfectoConversion",
]
export const ValuesNames = {
    "Total" : "Total",
    "ValorContable": "Valor Contable",
    "EfectoConversion": "Efecto Conversión",
    "MenorValorFiscal": "Menor Valor Fiscal", 
    "MayorValorFiscal": "Mayor Valor Fiscal",
    "ValorFiscal": "Valor Fiscal",
    "ActivosEquivalentesEfectivo" : "Efectivo y equivalentes al efectivo",
    "Efectivo" : "Efectivo",
    "EquivalentesEfectivo" : "Equivalentes al efectivo",
    "EfectivoRestringido" : "Efectivo restringido ",
    "InversionesInstrumentosFinancierosDerivadosVN" :"Inversiones e instrumentos financieros derivados (valor neto)",
    "InversionesInstrumentosFinancierosDerivados":"Inversiones e instrumentos financieros derivados",
    "DerechosRecompraInversiones" : "Derechos de recompra de inversiones",
    "InversionesSubsidiariasAsociadasNegociosConjuntos" : "Inversiones en subsidiarias, asociadas y negocios conjuntos",
    "ValorRazonableCambiosResultados" : "Valor razonable con cambios en resultados",
    "ValorRazonableCambiosORI" : "Valor razonable con cambios en el ORI",
    "MetodoParticipacion" : "Método de participación",
    "AlCosto" : "Al costo",
    "InstrumentosDeudaCostoAmortizado" : "Instrumentos de deuda a costo amortizado",
    "InstrumentosDeudaPatrimonioCosto": "Instrumentos de deuda o patrimonio al costo",
    "InstrumentosDeudaPatrimonioValorRazonableResultados" : "Instrumentos de deuda o patrimonio al valor razonable con cambios en resultados",
    "InstrumentosDeudaPatrimonioValorRazonableORI" : "Instrumentos de deuda o patrimonio al  valor razonable con cambios en el ORI",
    "InstrumentosFinancierosDerivadosNegociación" : "Instrumentos financieros derivados con fines de negociación",
    "InstrumentosFinancierosDerivadosCobertura" : "Instrumentos financieros derivados con fines de cobertura",
    "DerechosFiduciarios" : "Derechos fiduciarios",
    "Otros" : "Otros",
    "DeterioroAcumuladoInversiones" : "Deterioro acumulado de inversiones",
    "Metodo" : "Método de la participación",
    "Costo" : "Costo",
    "instrumentosDeudaCostoAmortizado" : "instrumentos de deuda a costo amortizado",
    "InstrumentosDeudaPatrimoniooCosto" : "Instrumentos de deuda o patrimonio al costo",
    "CuentasComercialesCobrarOtrasPorCobrar" : "Cuentas comerciales por cobrar y otras cuentas por cobrar",
    "CuentasDocumentosPorCobrar" : "Cuentas comerciales por cobrar y otras cuentas por cobrar",
    "CarteraCreditoPrestamosBancarios" : "Cartera de crédito (préstamos bancarios)",
    "CuentasComercialesPorCobrar" : "Cuentas comerciales por cobrar",
    "CuentasPorCobrarAcuerdosConcesion" : "Cuentas por cobrar en acuerdos de concesión (modelo del activo financiero)",
    "ArrendamientoFinancieroOLeasingFinanciero" : "Arrendamiento financiero o leasing financiero",
    "DividendosParticipaciones" : "Dividendos y participaciones",
    "CuentasPorCobrarSociosAccionistasParticipes" : "Cuentas por cobrar a socios, accionistas o partícipes",
    "CuentasDocumentosPorCobrarOtrasPartesRelacionadasAsociadas" : "Cuentas y documentos por cobrar a otras partes relacionadas y asociadas",
    "PrimasSegurosPorRecaudar" : "Primas de seguros por recaudar",
    "CarteraDificilCobro" : "Cartera de difícil cobro",
    "ReclamacionesPorCobrar" : "Reclamaciones por cobrar",
    "AnticiposPagos" : "Anticipos de pagos",
    "OtrasCuentasDocumentosPorCobrar" : "Otras cuentas y documentos por cobrar",
    "DeterioroAcumuladoValorCuentasDocumentosCobrar" : "Deterioro acumulado del valor cuentas y documentos por cobrar",
    "CarteraDeCredito" : "Cartera de crédito (préstamos bancarios)",
    "ArrendamientoFinancieroLeasingFinanciero" : "Arrendamiento financiero o leasing financiero",
    "CuentasPorCobrarOtrasPartesRelacionadasAsociadas" : "Cuentas por cobrar a otras partes relacionadas y asociadas",
    "OtrasCuentasPorCobrar" : "Otras cuentas por cobrar",
    "Inventarios" : "Inventarios" ,
    "ParaLaVentaNoProducidosPorLaEmpresa" : "Para la venta, no producidos por la empresa" ,
    "EnTransito" : "En tránsito" ,
    "MateriasPrimasSuministrosMateriales" : "Materias primas, suministros y materiales" ,
    "EnProcesoDiferentesDeObrasInmueblesEnConstruccionParaVenta" : "En proceso (diferentes de obras o inmuebles en construcción para la venta)" ,
    "CostosPrestadoresServicios" : "Costos prestadores de servicios" ,
    "ProductoTerminadoDiferentesObrasInmueblesTerminadosParaVenta" : "Producto terminado (diferentes de obras o inmuebles terminados para la venta)" ,
    "ObrasInmueblesConstruccionParaVenta" : "Obras o inmuebles en construcción para la venta" ,
    "ObrasInmueblesTerminadosParaVenta" : "Obras o inmuebles terminados para la venta" ,
    "PiezasRepuestoEquipoAuxiliarClasificadosComoInventarios" : "Piezas de repuesto y equipo auxiliar clasificados como inventarios" ,
    "InventarioSurgeActividadExtraccion" : "Inventario que surge de la actividad de extracción" ,
    "DeterioroAcumuladoValorInventarios" : "Deterioro acumulado del valor de inventarios" ,
    "GastosPagadosPorAnticipado" : "Gastos pagados por anticipado" ,
    "Publicidad" : "Publicidad" ,
    "PrimasSeguros" : "Primas de seguros" ,
    "Arrendamientos" : "Arrendamientos" ,
    "ActivosImpuestosCorrientes" : "Activos por impuestos corrientes",
    "SaldosaFavor" : "Saldos a favor por el impuesto de renta",
    "SaldosaFavorOtrosImpuestos" : "Saldos a favor - otros impuestos y gravámenes",
    "DescuentosTributarios" : "Descuentos tributarios",
    "AnticiposyOtros" : "Anticipos y otros",
    "ActivosImpuestosDiferidos" : "Activos por impuestos diferidos",
    "PropiedadesPlantaEquipo" : "Propiedades, planta y equipo",
    "Terrenos" : "Terrenos",
    "ConstruccionesEnProceso" : "Construcciones en proceso ",
    "Edificios" : "Edificios",
    "AjusteAcumuladoRevaluacionesReexpresiones" : "Ajuste acumulado por revaluaciones o reexpresiones",
    "ActivosTangiblesExploracionEvaluacionRecursosMinerales" : "Activos tangibles para exploración y evaluación de recursos minerales",
    "OtrasPropiedadesPlantaEquipo" : "Otras propiedades, planta y equipo",
    "DepreciacionAcumuladaPropiedadesPlantaEquipo" : "Depreciación acumulada de propiedades, planta y equipo",
    "DeterioroAcumuladoPropiedadesPlantaEquipo" : "Deterioro acumulado de propiedades, planta y equipo",
    "ActivosIntangibles" : "Activos intangibles" ,
    "ActivosIntangiblesDistintosPlusvalia" : "Activos intangibles distintos a la plusvalía" ,
    "AcuerdosConcesionActivoIntangible" : "Acuerdos de concesión (modelo del activo intangible)" ,
    "ActivosIntangiblesExploracionEvaluacionRecursosMinerales" : "Activos intangibles exploración y evaluación de recursos minerales" ,
    "MarcasPatentesLicenciasOtrosDerechos" : "Marcas, patentes, licencias y otros derechos" ,
    "ArrendamientoFinanciero" : "Arrendamiento Financiero" ,
    "OtrosActivosIntangibles" : "Otros activos intangibles" ,
    "AmortizacionAcumuladaActivosIntangiblesDistintosPlusvalia" : "Amortización acumulada de activos intangibles distintos de la plusvalía" ,
    "DeterioroAcumuladoActivosIntangiblesDistintosPlusvalia" : "Deterioro acumulado de activos intangibles distintos de la plusvalía" ,
    "PlusvaliaGoodwill" : "Plusvalía o Good Will" ,
    "AdquisicionEstablecimientoComercio" : "Adquisición de establecimiento de comercio" ,
    "Fusiones" : "Fusiones" ,
    "Escisiones" : "Escisiones" ,
    "CompraAcciones" : "Compra de acciones" ,
    "AmortizacionAcumuladaPlusvaliaGoodwill" : "Amortización acumulada de la plusvalía o Good Will" ,
    "DeterioroAcumuladoPlusvaliaGoodwill" : "Deterioro acumulado de la plusvalía o Good Will  " ,
    "PropiedadesInversion" : "Propiedades de inversión" ,
    "TerrenoEdificios" : "Terrenos y edificios" ,
    "AlValorRazonable" : "Al valor razonable" ,
    "DepreciacionAcumuladaPropiedadesInversion" : "Depreciación acumulada de propiedades de inversión   " ,
    "DeterioroAcumuladoPropiedadesInversion" : "Deterioro acumulado de propiedades de inversión" ,
    "ActivosNoCorrientes" : "Activos no corrientes" ,
    "MantenidosParaVenta" : "Mantenidos para la venta" ,
    "DeterioroAcumuladoActivosCorrientesMantenidosParaVenta" : "Deterioro acumulado activos no corrientes mantenidos para la venta" ,
    "MantenidosParaDistribuirPropietarios" : "Mantenidos para distribuir a los propietarios" ,
    "DeterioroAcumuladoActivosCorrientesMantenidosParaDistribuirPropietarios" : "Deterioro acumulado activos no corrientes mantenidos para distribuir a los propietarios" ,
    "ActivosBiologicos" : "Activos biológicos" ,
    "AnimalesVivos" : "Animales vivos" ,
    "AnimalesProductoresMedidosAlCosto" : "Animales productores medidos al costo" ,
    "DepreciacionAcumuladaDeAnimalesProductoresMedidosAlCosto" : "Depreciación acumulada de animales productores medidos al costo " ,
    "DeterioroAcumuladoDeAnimalesProductoresMedidosAlCosto" : "Deterioro acumulado de animales productores medidos al costo " ,
    "AnimalesProductoresMedidosAlValorRazonableMenosCostosDeVenta" : "Animales productores medidos al valor razonable menos costos de venta" ,
    "AnimalesConsumiblesMedidosAlCosto" : "Animales consumibles medidos al costo" ,
    "DeterioroAcumuladoAnimalesConsumiblesMedidosAlCosto" : "Deterioro acumulado animales consumibles medidos al costo" ,
    "AnimalesConsumiblesMedidosAlValorRazonableMenosCostosDeVenta" : "Animales consumibles medidos al valor razonable menos costos de venta" ,
    "PlantasProductorasCultivosConsumibles" : "Plantas productoras y cultivos consumibles" ,
    "PlantasProductorasMedidasAlCosto" : "Plantas productoras medidas al costo" ,
    "DepreciacionAcumuladaDePlantasProductoras" : "Depreciación acumulada de plantas productoras" ,
    "DeterioroAcumuladoDePlantasProductoras" : "Deterioro acumulado de plantas productoras" ,
    "PlantasProductorasMedidasAlValorRazonable" : "Plantas productoras medidas al valor razonable" ,
    "CultivosConsumiblesMedidosAlCosto" : "Cultivos consumibles medidos al costo" ,
    "DeterioroAcumuladoCultivosConsumiblesMedidosAlCosto" : "Deterioro acumulado cultivos consumibles medidos al costo" ,
    "CultivosConsumiblesMedidosAlValorRazonableMenosCostosDeVenta" : "Cultivos consumibles medidos al valor razonable menos costos de venta" ,
    "OtrosActivos" : "Otros activos" ,
    "ActivosPlanBeneficiosEmpleados" : "Activos plan de beneficios a empleados" ,
    "ActivosReconocidosSolamenteFinesFiscales" : "Activos reconocidos solamente para fines fiscales" ,
    "ObligacionesFinancierasCuentasPorPagar" : "Obligaciones financieras y cuentas por pagar" ,
    "ObligacionesFinancierasEnMonedaLocal" : "Obligaciones financieras en moneda local" ,
    "ObligacionesFinancierasEnMonedaExtranjera" : "Obligaciones financieras en moneda extranjera" ,
    "DepositosYExigibilidades" : "Depósitos y exigibilidades" ,
    "CuentasComercialesPorPagarEnMonedaLocal" : "Cuentas comerciales por pagar en moneda local" ,
    "CuentasComercialesPorPagarEnMonedaExtranjera" : "Cuentas comerciales por pagar en moneda extranjera" ,
    "DividendosYParticipacionesPorPagar" : "Dividendos y participaciones por pagar" ,
    "CuentasPorPagarASociosAccionistasOParticipes" : "Cuentas por pagar a socios, accionistas o partícipes" ,
    "CuentasYDocumentosPorPagarAOtrasPartesRelacionadasYAsociadas" : "Cuentas y documentos por pagar a otras partes relacionadas y asociadas" ,
    "ReservaMatematicaYOTecnicaYOtrosPasivosExclusivosEnCompaniasDeSeguros" : "Reserva matemática y/o técnica y otros pasivos exclusivos en compañías de seguros" ,
    "RecaudoAFavorDeTerceros" : "Recaudo a favor de terceros" ,
    "OtrasCuentasYDocumentosPorPagarEnMonedaLocal" : "Otras cuentas y documentos por pagar en moneda local" ,
    "OtrasCuentasYDocumentosPorPagarEnMonedaExtranjera" : "Otras cuentas y documentos por pagar en moneda extranjera" ,
    "ArrendamientosPorPagar" : "Arrendamientos por pagar" ,
    "FinancieroLeasingPartesNoRelacionadas" : "Financiero o leasing - partes no relacionadas" ,
    "FinancieroLeasingPartesRelacionadas" : "Financiero o leasing - partes relacionadas" ,
    "Operativo" : "Operativo" ,
    "OtrosPasivosFinancieros" : "Otros pasivos financieros" ,
    "BonosYDocumentosEquivalentes" : "Bonos y documentos equivalentes" ,
    "InstrumentosFinancierosDerivados" : "Instrumentos financieros derivados " ,
    "AccionesPreferencialesOAportesDeCapitalClasificadosComoPasivos" : "Acciones preferenciales o aportes de capital clasificados como pasivos" ,
    "ImpuestosGravamenesTasasPorPagar" : "Impuestos, gravámenes y tasas por pagar" ,
    "ImpuestoRenta" : "Impuesto de renta" ,
    "IVA" : "Impuesto al valor agregado - IVA" ,
    "Otrosimpuestos" : "Otros impuestos, gravámenes y tasas por pagar" ,
    "PasivosImpuestosDiferidos" : "Pasivos por impuestos diferidos" ,
    "PasivosBeneficiosEmpleados" : "Pasivos por beneficios a los empleados" ,
    "CortoPlazo" : "De corto plazo" ,
    "LargoPlazo" : "De largo plazo" ,
    "TerminacionVinculosLaborales" : "Por terminación del vínculo laboral o contractual" ,
    "PostEmpleo" : "Post empleo" ,
    "Provisiones" : "Provisiones",
    "procesosLegalesLitigiosYDemandas" : "Procesos legales (litigios y demandas)" ,
    "mantenimientoYReparaciones" : "Mantenimiento y reparaciones" ,
    "obligacionesFiscales" : "Obligaciones fiscales" ,
    "desmantelamientosRestauracionYRehabilitacion" : "Desmantelamientos, restauración y rehabilitación" ,
    "garantias" : "Garantías" ,
    "contratosOnerosos" : "Contratos onerosos" ,
    "reembolsosAClientes" : "Reembolsos a clientes" ,
    "reestructuracionesDeNegocios" : "Reestructuraciones de negocios" ,
    "pasivosContingentesAsumidosEnUnaCombinacionDeNegocios" : "Pasivos contingentes asumidos en una combinación de negocios" ,
    "relacionadasConElMedioAmbiente" : "Relacionadas con el medio ambiente" ,
    "otrasProvisiones" : "Otras provisiones" ,
    "PasivosIngresosDiferidos" : "Pasivos por ingresos diferidos" ,
    "AnticiposYAvancesRecibidosDeClientes" : "Anticipos y avances recibidos de clientes" ,
    "IngresosDiferidosPorProgramasDeFidelizacion" : "Ingresos diferidos por programas de fidelización" ,
    "SubvencionesDelGobiernoYOtrasAyudas" : "Subvenciones del gobierno y otras ayudas" ,
    "OtrosPasivosPorIngresosDiferidos" : "Otros pasivos por ingresos diferidos" ,
    "OtrosPasivos" : "Otros pasivos" ,
    "DepositosRecibidos" : "Depósitos recibidos" ,
    "RetencionesATercerosSobreContratos" : "Retenciones a terceros sobre contratos" ,
    "EmbargosJudiciales" : "Embargos judiciales" ,
    "CuentasEnParticipacion" : "Cuentas en participación" ,
    "PasivoParaEjecucionDeExcedentesESAL" : "Pasivo para ejecución de excedentes - ESAL " ,
    "FondosSocialesMutualesYOtros" : "Fondos sociales, mutuales y otros" ,
    "PasivosReconocidosSolamenteParaFinesFiscales" : "Pasivos reconocidos solamente para fines fiscales" ,
    "TotalPatrimonio" : "PATRIMONIO (ACTIVOS - PASIVOS)",
    "CapitalSocialReservas" : "Capital social y reservas",
    "CapitalPagado" : "Capital pagado",
    "AccionesCuotasPartesInteresSocialPropiasCartera" : "Acciones, cuotas o partes de interés social propias en cartera",
    "AportesSociales" : "Aportes sociales",
    "CapitalAsignado" : "Capital asignado",
    "FondoSocialMutual" : "Fondo social mutual",
    "SuperavitCapital" : "Superávit de capital",
    "Donaciones" : "Donaciones",
    "ReservasLegalesEstatutarias" : "Reservas legales o estatutarias",
    "ReservasOcasionales" : "Reservas ocasionales",
    "ReservasFondosEntidadesSolidarias" : "Reservas y fondos entidades solidarias",
    "AsignacionesPermanentesRegimenTributarioEspecial" : "Asignaciones permanentes - Régimen Tributario Especial",
    "SuperavitRevaluaciones" : "Superávit por revaluaciones",
    "SuperavitMetodoParticipacion" : "Superávit método de participación",
    "DividendosParticipacionesDecretadosAccionesCuotasPartesInteresSocial" : "Dividendos o participaciones decretados en acciones, cuotas o partes de interés social",
    "SaldoCreditoInversionSuplementaria" : "Saldo crédito inversión suplementaria",
    "SaldoDebitoInversionSuplementaria" : "Saldo débito inversión suplementaria",
    "ResultadoEjercicio" : "Resultados del ejercicio",
    "UtilidadOExcedenteDelEjercicioEnOperacionesContinuadas" : "Utilidad o excedente del ejercicio en operaciones continuadas",
    "UtilidadOExcedenteDelEjercicioEnOperacionesDiscontinuadas" : "Utilidad o excedente del ejercicio en operaciones discontinuadas",
    "PerdidaODeficitDelEjercicioEnOperacionesContinuadas" : "Pérdida o déficit del ejercicio en operaciones continuadas",
    "PerdidaODeficitDelEjercicioEnOperacionesDiscontinuadas" : "Pérdida o déficit del ejercicio en operaciones discontinuadas",
    "ResultadosAcumulados" : "Resultados acumulados",
    "UtilidadesOExcedentesAcumuladosSusceptiblesDeDistribucionATituloDeNoConstitutivoDeRentaNiGananciaOcasional" : "Utilidades o excedentes acumulados susceptibles de distribución a titulo de no constitutivo de renta ni ganancia ocasional",
    "UtilidadesOExcedentesAcumuladosSusceptiblesDeDistribucionEnCalidadDeGravados" : "Utilidades o excedentes acumulados susceptibles de distribución en calidad de gravados",
    "UtilidadesAcumuladasPorAjustesPorCorreccionDeErrores" : "Utilidades acumuladas por ajustes por corrección de errores",
    "UtilidadesPorAjustesPorCambiosEnPoliticasContables" : "Utilidades por ajustes por cambios en políticas contables",
    "PerdidasODeficitAcumulados" : "Pérdidas o déficit acumulados",
    "PerdidasAcumuladasPorAjustesPorCorreccionesDeErrores" : "Pérdidas acumuladas por ajustes por correcciones de errores",
    "PerdidasPorAjustesPorCambiosEnPoliticasContables" : "Pérdidas  por ajustes por cambios en políticas contables ",
    "GananciasPerdidasAcumuladasRetenidasAdopcionPrimera" : "Ganancias (pérdidas) acumuladas o retenidas por la adopción por primera",
    "GananciasPrimeraVez" : "Ganancias acumuladas netas en la adopción por primera vez",
    "PerdidasPrimeraVez" : "Pérdidas acumuladas netas - adopción por primera vez",
    "OtroResultadoIntegralAcumulado" : "Otro resultado integral acumulado",
    "AjustePositivoPorEfectoConversion" : "Ajuste positivo por efecto de conversión",
    "AjusteNegativoPorEfectoConversion" : "Ajuste negativo por efecto de conversión",
    "GananciasAcomuladasORI" : "Ganancias acumuladas - ORI",
    "PerdidasAcumuladasORI" : "Pérdidas acumuladas - ORI",
    "DatosInformativos" : "DATOS INFORMATIVOS",
    "TotalIntereses" : "Total de intereses implícitos no devengados (futuros ingresos financieros en el estado de resultados) por acuerdos que constituyen efectivamente una transacción financiera o cobro diferido",
    "TotalActivos" : "Total activos (fideicomitidos y generados) en el periodo gravable por fideicomisos o encargos fiduciarios en donde el contribuyente es fideicomitente o fiduciante",
    "InventariosTerceros" : "Inventarios de terceros",
    "InventariosPoderTerceros" : "Inventarios en poder de terceros",
    "TotalInteresespasivos" : "Total de intereses implícitos no devengados (futuros gastos financieros en el estado de resultados) por acuerdos que constituyen efectivamente una transacción financiera o pago diferido",
    "TotalPasivos" : "Total pasivos (fideicomitidos y generados) en el periodo gravable por fideicomisos o encargos fiduciarios en donde el contribuyente es fideicomitente o fiduciante",
    "RetencionFuenteTrasladableArt2421ET" : "Retención en la fuente trasladable (art. 242-1 del ET)",
    "DividendosGravadosDecretadosPeriodo" : "Dividendos o participaciones gravados decretados en el periodo",
    "DividendosNoGravadosDecretadosPeriodo" : "Dividendos o participaciones no gravados decretados en el periodo",
    "DividendosGravadosPagadosPeriodo" : "Dividendos o participaciones gravados efectivamente pagados o exigibles en el periodo",
    "DividendosNoGravadosPagadosPeriodo" : "Dividendos o participaciones no gravados efectivamente pagados o exigibles en el periodo",
    "DividendosGravadosPagadosPeriodoCargoUtilidades" : "Dividendos o participaciones pagados o exigibles en el periodo, con cargo a utilidades del mismo período",
    "TotalPatrimonio.ValorContable": "Valor Contable",
    "TotalPatrimonio.EfectoConversion": "Efecto Conversión",
    "TotalPatrimonio.MenorValorFiscal": "Menor Valor Fiscal",
    "TotalPatrimonio.MayorValorFiscal": "Mayor Valor Fiscal",
    "TotalPatrimonio.ValorFiscal": "Valor Fiscal",

};
export const TabsNames = {
    "Activos" : "Activos",
    "Pasivos" : "Pasivos",
    "TotalPatrimonio" : "Patrimonio",
    "PatrimonioContable" : "Patrimonio Contable",
    "DatosInformativos" : "Datos Informativos"
}
export const excludedCalculateValorFiscalInputs = [
    "Total",
]