export const friendlyNames = {
  OtrosReconocidosFinesFiscales: "Activos reconocidos solamente para fines fiscales",
  BaseContable: "Base contable",
  BaseFiscal: "Base Fiscal",
  DiferenciaTemporaria: "Diferencia Temporaria",
  DiferenciaPermanente: "Diferencia Permanente",
  SaldoImpuestoDiferidoActual:
    "Saldo impuesto diferido a 31 -DIC vigencia actual",
  SaldoImpuestoDiferidoAnterior:
    "Saldo impuesto diferido a 31 -DIC vigencia anterior",
  Variacion: "Variación",
  TasaFiscalAplicada: "Tasa fiscal aplicada",
  Saldo31VigenciaActual: "Saldo impuesto diferido a 31 -DIC vigencia actual",
  Saldo31VigenciaAnterior:
    "Saldo impuesto diferido a 31 -DIC vigencia  anterior",
  ReduccionCompensacion: "Reducción (compensación / aplicación)",
  CorreccionMayorValor: "Correción mayor valor",
  CorreccionMenorValor: "Correción menor valor",
  AjusteMayorValor: "Ajuste mayor valor",
  AjusteMenorValor: "Ajuste menor valor",
  Anio: "Año",
  PerdidasFiscalesAcumuladasCompensarInicio:
    "Pérdidas fiscales acumuladas por compensar al inicio del periodo",
  PerdidaFiscalGeneradaPeriodo: "Pérdida fiscal generada en el periodo (+)",
  PerdidaFiscalCompensadaPeriodo: "Pérdida fiscal compensada en el período (-)",
  ValoresNoCompesados: "Valores no compensados por caducidad (-)",
  AjustesMayorValor: "Ajustes mayor valor",
  AjustesMenorValor: "Ajustes menor valor",
  PerdidaFiscalAcumuladaCompensarFinal:
    "Pérdida fiscal acumulada por compensar al final del periodo",
  SaldoActivoImpuestoDiferido:
    "Saldo activo por impuesto diferido al final del período",
  ValorAcumuladoCompensarInicioPeriodo:
    "Valor acumulado por compensar al inicio del periodo",
  ValorGeneradoPeriodo: "Valor generado en el periodo (+)",
  ValorCompensadoPeriodo: "Valor compensado en el período (-)",
  ValoresNoCompensados: "Valores no compensados por caducidad (-)",
  ValorAcumuladoCompensarFinalPerido:
    "Valor acumulado por compensar al final del periodo",
  SaldoActivoImpuestoDiferidoFinal:
    "Saldo activo por impuesto diferido al final del período",
  EfectivoYEfectivoEquivalente: "Efectivo y equivalentes al efectivo",
  InversionesEInstrumentosDerivados: "Inversiones e instrumentos derivados",
  CuentasPorCobrar: "Cuentas por cobrar",
  Inventarios: "Inventarios",
  PropiedadesPlantaYEquipo: "Propiedades, planta y equipo",
  ActivosIntangibles: "Activos intangibles",
  PropiedadesDeInversion: "Propiedades de inversión",
  ActivosBiologicos: "Activos biológicos",
  EntregarAPropietarios: "Activos no corrientes mantenidos para la venta / entregar a propietarios",
  PasivosFinancierosYCuentasPorPagar: "Pasivos financieros y cuentas por pagar",
  ImpuestosGravamenesYTasas: "Impuestos, gravámenes y tasas",
  BeneficiosAEmpleados: "Beneficios a  Empleados",
  Provisiones: "Provisiones",
  OtrosPasivosAnticiposYAvancesRecibidos: "Otros Pasivos Anticipos y avances recibidos",
  OperacionesConTitulosYDerivados: "Operaciones con títulos y derivados",
  PerdidasFiscalesYExcesosDeRentaPresuntiva: "Perdidas fiscales y/o excesos de renta presuntiva",
  Fiscales: "Perdidas fiscales y/o excesos de renta presuntiva",
  OtrosActivos: "Otros activos",
  SaldosFavor: "Saldos a favor",
  ImpuestosPagadosExterior: "Impuestos pagados en el exterior",
};

export const calculatedValues = [
  "EfectivoYEfectivoEquivalente.Variacion",
  "Variacion",
  "DiferenciaTemporaria",
  "SaldoImpuestoDiferidoActual",
  "TasaFiscalAplicada",
  "PerdidaFiscalAcumulada",
  "SaldoActivoImpuestoDiferido",
  "Actual.ValorGeneradoPeriodo",
  "Actual.PerdidaFiscalGeneradaPeriodo",
  "Actual.PerdidaFiscalCompensadaPeriodo",
  "ReduccionCompensacion",
  "ImpuestosPagadosExterior.Saldo31VigenciaActual",
  "ImpuestosPagadosExterior.Saldo31VigenciaAnterior",
  "ImpuestosPagadosExterior.ReduccionCompensacion",

  "EfectivoYEfectivoEquivalente.BaseContable",
  "InversionesEInstrumentosDerivados.BaseContable",
  "CuentasPorCobrar.BaseContable",
  "Inventarios.BaseContable",
  "PropiedadesPlantaYEquipo.BaseContable",
  "ActivosIntangibles.BaseContable",
  "PropiedadesDeInversion.BaseContable",
  "ActivosBiologicos.BaseContable",
  "EntregarAPropietarios.BaseContable",
  "PasivosFinancierosYCuentasPorPagar.BaseContable",
  "ImpuestosGravamenesYTasas.BaseContable",
  "BeneficiosAEmpleados.BaseContable",
  "Provisiones.BaseContable",
  "OtrosPasivosAnticiposYAvancesRecibidos.BaseContable",
  "OtrosActivos.BaseContable",

  "CuentasPorCobrar.BaseFiscal",
  "EfectivoYEfectivoEquivalente.BaseFiscal",
  "InversionesEInstrumentosDerivados.BaseFiscal",
  "CuentasPorCobrar.BaseFiscal",
  "Inventarios.BaseFiscal",
  "PropiedadesPlantaYEquipo.BaseFiscal",
  "ActivosIntangibles.BaseFiscal",
  "PropiedadesDeInversion.BaseFiscal",
  "ActivosBiologicos.BaseFiscal",
  "EntregarAPropietarios.BaseFiscal",
  "PasivosFinancierosYCuentasPorPagar.BaseFiscal",
  "ImpuestosGravamenesYTasas.BaseFiscal",
  "BeneficiosAEmpleados.BaseFiscal",
  "Provisiones.BaseFiscal",
  "OtrosPasivosAnticiposYAvancesRecibidos.BaseFiscal",
  "OtrosActivos.BaseFiscal",
];

export const excludedValues = ["PasivoDiferido.OtrosPasivosAnticiposYAvancesRecibidos.BaseFiscal", "PasivoDiferido.OtrosPasivosAnticiposYAvancesRecibidos.BaseContable"];
