export const ImpuestoDiferidoEq = {
    "BaseContable": "Base contable",
    "BaseFiscal": "Base Fiscal",
    "DiferenciaTemporaria": "Diferencia Temporaria",
    "DiferenciaPermanente": "Diferencia Permanente",
    "SaldoImpuestoDiferidoActual": "Saldo impuesto diferido a 31 -DIC vigencia actual",
    "SaldoImpuestoDiferidoAnterior": "Saldo impuesto diferido a 31 -DIC vigencia anterior",
    "Variacion": "Variación",
    "TasaFiscalAplicada": "Tasa fiscal aplicada",
    "Saldo31VigenciaActual": "",
    "Saldo31VigenciaAnterior": "",
    "ReduccionCompensacion": "",
    "CorreccionMayorValor": "",
    "CorreccionMenorValor": "",
    "AjusteMayorValor": "",
    "AjusteMenorValor": "",
    "Anio": "",
    "PerdidasFiscalesAcumuladasCompensarInicio": "",
    "PerdidaFiscalGeneradaPeriodo": "",
    "PerdidaFiscalCompensadaPeriodo": "",
    "ValoresNoCompesados": "",
    "AjustesMayorValor": "",
    "AjustesMenorValor": "",
    "PerdidaFiscalAcumuladaCompensarFinal": "",
    "SaldoActivoImpuestoDiferido": "",
    "ValorAcumuladoCompensarInicioPeriodo": "",
    "ValorGeneradoPeriodo": "",
    "ValorCompensadoPeriodo": "",
    "ValoresNoCompensados": "",
    "ValorAcumuladoCompensarFinalPerido": "",
    "SaldoActivoImpuestoDiferidoFinal": ""
}