export const rentaLiquidaNames = {
    Ingresos: "Ingresos",
    IngresosNetosActividadIndustrialCoSer: "Ingresos netos Actividad Industrial, comercial y servicios",
    VentaTerritorioNacional: "Venta en territorio nacional",
    VentaExportacion: "Venta en exportación a otros países",
    VentaZonaFranca: "Venta en zona franca",
    VentaComercializadorasInternacionales: "Venta a comercializadoras internacionales",
    VentaJurisdiccionesNoCooperantes: "venta jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    VentaVinculadoEconomicosFranca: "Venta vinculado Económicos zona Franca y exterior",
    PrestacionServiciosTerritorioNacional: "Prestación de servicios al territorio nacional",
    PrestacionServiciosExportacion: "Prestación de servicios en exportación a otros países",
    PrestacionServiciosZonaFranca: "Prestación de servicios en zona franca",
    PrestacionServiciosComercializadorasInternacionales: "Prestación de servicios a comercializadoras internacionales",
    PrestacionServiciosJurisdiccionesNoCooperantes: "Prestación de servicios a jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    PrestacionServiciosVinculadoEconomicosFranca: "Prestación de servicios a vinculado Económicos zona Franca y exterior",
    ServiciosConstruccion: "Servicios de construcción",
    AcuerdosConcesion: "Acuerdos de concesión de servicios",
    ArrendamientosOperativos: "Arrendamientos operativos",
    Regalias: "Regalías",
    Comisiones: "Comisiones (relaciones de agencia)",
    HonorariosProfesionales: "Honorarios profesionales",
    ActividadesSegurosCapitalizacion: "Actividades de seguros y capitalización",
    LiberacionReservasContratosSeguros: "Liberación de reservas en contratos de seguros",
    ComisionesBancarias: "Comisiones bancarias, costos de transacción enre otros",
    OtrosIngresos: "Otros ingresos",
    DevolucionesRebajasDescuentos: "Devoluciones, rebajas y descuentos",
    VentaBienes: "Venta de bienes",
    PrestacionServicios: "Prestación de servicios",
    OtrasDevoluciones: "Otras devoluciones",
    IngresosFinancieros: "Ingresos financieros",
    ArrendamientoFinanciero: "Arrendamiento financiero o mercantil (leasing)",
    InteresesSectorFinanciero: "Intereses - sector financiero",
    InteresesPrestamosTerceros: "Intereses por préstamos a terceros (diferentes al sector financiero)",
    IntrumentosFinancierosMedidos: "Instrumentos financieros medidos a costo amortizado distinto a préstamos",
    InteresesImplicitos: "Intereses implícitos (transacciones de financiación)",
    DiferenciaCambio: "Diferencia en cambio",
    GananciasInversionesSubsidiariasAsociadasNegocios: "GananciasInversionesSubsidiariasAsociadasNegocios",
    GananciasMetodoParticipacion: "Ganancias por el método de participación",
    GananciasCambioValorRazonable: "Ganancias por cambio en el valor razonable",
    DividendosParticipacionesNoContribuyentes: "Dividendos y/o participaciones NO constitutivos de renta ni ganancia ocasional (incluye capitalizaciones no gravadas)",
    DividendosParticipacionesDistribuidosEntidadesNoColombia: "Dividendos o participaciones distribuidos por entidades no residentes en Colombia a una CHC y prima en colocación de acciones. ",
    DividendosParticipacionesGravadasTarifaGeneral: "Dividendos y/o participaciones gravadas a la tarifa general provenientes de sociedades y entidades extranjeras o de sociedades nacionales.",
    DividendosParticipacionesGravadasPersonaNatural: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2016 y anteriores)",
    DividendosParticipacionesGravadasPersonaNaturalSinResidencia: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2017 y siguientes) ",
    DividendosParticipaciones10: "Dividendos y/o participaciones gravadas al 10%",
    DividendosParticipacionesGravadasTarifaGeneralExtranjeras: "Dividendos y/o participaciones gravadas a tarifa general (EP y sociedades extranjeras - utilidades generadas a partir del año 2017) ",
    DividendosProyectosMegainversion: "Dividendos y participaciones provenientes de proyectos calificados como mega inversión gravadas al 27% ",
    IngresosPorMedicionesValorRazonable: "Ingresos por mediciones al valor razonable",
    ActivosBiologicos: "Activos biológicos",
    PropiedadesInversion: "Propiedades de inversión",
    InstrumentosFinancieros: "Instrumentos financieros, diferente a inversiones en subsidiarias, asociadas y/o negocios conjuntos ",
    InstrumentosDerivados: "Instrumentos derivados",
    UtilidadVentaEnajenacionActivosMenos2Anos: "Utilidad en la venta o enajenación de activos, bienes poseídos por menos de dos años",
    PropiedadesPlanta: "Propiedades, planta y equipo",
    ActivosNoCorrientesMantenidosVentaEntregarPropietarios: "Activos no corrientes mantenidos para la venta / entregar a propietarios",
    ActivosIntangibles: "Activos intangibles",
    InversionesAccionesOtrasParticipaciones: "Inversiones en acciones y otras participaciones",
    DisposicionOtrosInstrumentosFinancieros: "Disposición de otros instrumentos financieros",
    UtilidadVentaEnajenacionActivosMas2Anos: "Utilidad por venta o enajenación de activos, bienes poseídos por dos años o más (ganancia ocasional)",
    IngresosReversionDeterioroValor: "Ingresos por reversión de deterioro del valor",
    Inventarios: "Inventarios",
    PropiedadesPlantaEquipo: "Propiedades, planta y equipo",
    ActivosExploracionEvaluacionRecursosMinerales: "Activos de exploración y evaluación de recursos minerales",
    PropiedadesInversionMedidasCosto: "Propiedades de inversión medidas al costo",
    ActivosBiologicosMedidosCosto: "Activos biológicos medidos al modelo de costo",
    BienesArteCultura: "Bienes de arte y cultura",
    ActivosFinancieros: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)",
    CarteraCreditoOperacionesLeasing: "Cartera de crédito y operaciones de leasing",
    OtrasInversionesMedidasCostoMetodoParticipacion: "Otras inversiones medidas al costo o el método de la participación",
    OtrosDeterioros: "Otros deterioros",
    IngresosReversionProvisiones: "Ingresos por reversión de provisiones (pasivos de monto o fecha inciertos)",
    Garantias: "Garantías",
    ContratosOnerosos: "Contratos onerosos",
    Litigios: "Litigios",
    ReembolsosClientes: "Reembolsos a clientes",
    ReestructuracionesNegocios: "Reestructuraciones de negocios",
    PasivosContingentesCombinacionNegocios: "Pasivos contingentes asumidos en una combinación de negocios",
    IngresosReversionPasivosBeneficiosEmpleados: "Ingresos por reversión de pasivos por beneficios a los empleados",
    BeneficiosDeCortoPlazo: "Beneficios de corto plazo",
    BeneficiosDeLargoPlazo: "Beneficios de largo plazo",
    BeneficiosAEmpeladosPorTerminacionDelVinculoLaboral: "Beneficios a empleados por terminación del vínculo laboral",
    BeneficiosAEmpeladosPostEmpleo: "Beneficios a empleados post-empleo",
    /**
     * TODO: linea 1336 del json
     */
}