export const calculateValorFiscalInputs = [
    "Ingresos",
    "Costos",
    "Gastos",
]

export const excludedCalculateValorFiscalInputs = [
    "MenorGastoDeduccionPrecioTransferencia",
    "GananciasMetodoParticipacion",
    "GananciasCambioValorRazonable",
    "GananciasNetasOperacionesDiscontinuas",
]

export const noInputsValues = [
    "ValorFiscal",
    "Total",
    "Otras",
    "TotalCostos",
    "TotalIngresos",
    "TotalGastos",
];

export const rentaLiquidaNames = {
    Ingresos: "Ingresos",
    IngresosNetosActividadIndustrialCoSer: "Ingresos netos Actividad Industrial, comercial y servicios",
    VentaTerritorioNacional: "Venta en territorio nacional",
    VentaExportacion: "Venta en exportación a otros países",
    VentaZonaFranca: "Venta en zona franca",
    VentaComercializadorasInternacionales: "Venta a comercializadoras internacionales",
    VentaJurisdiccionesNoCooperantes: "venta jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    VentaVinculadoEconomicosFranca: "Venta vinculado Económicos zona Franca y exterior",
    PrestacionServiciosTerritorioNacional: "Prestación de servicios al territorio nacional",
    PrestacionServiciosExportacion: "Prestación de servicios en exportación a otros países",
    PrestacionServiciosZonaFranca: "Prestación de servicios en zona franca",
    PrestacionServiciosComercializadorasInternacionales: "Prestación de servicios a comercializadoras internacionales",
    PrestacionServiciosJurisdiccionesNoCooperantes: "Prestación de servicios a jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    PrestacionServiciosVinculadoEconomicosFranca: "Prestación de servicios a vinculado Económicos zona Franca y exterior",
    ServiciosConstruccion: "Servicios de construcción",
    AcuerdosConcesion: "Acuerdos de concesión de servicios",
    ArrendamientosOperativos: "Arrendamientos operativos",
    Regalias: "Regalías",
    Comisiones: "Comisiones (relaciones de agencia)",
    HonorariosProfesionales: "Honorarios profesionales",
    ActividadesSegurosCapitalizacion: "Actividades de seguros y capitalización",
    LiberacionReservasContratosSeguros: "Liberación de reservas en contratos de seguros",
    ComisionesBancarias: "Comisiones bancarias, costos de transacción enre otros",
    OtrosIngresos: "Otros ingresos",
    DevolucionesRebajasDescuentos: "Devoluciones, rebajas y descuentos",
    VentaBienes: "Venta de bienes",
    PrestacionServicios: "Prestación de servicios",
    OtrasDevoluciones: "Otras devoluciones",
    IngresosFinancieros: "Ingresos financieros",
    ArrendamientoFinanciero: "Arrendamiento financiero o mercantil (leasing)",
    InteresesSectorFinanciero: "Intereses - sector financiero",
    InteresesPrestamosTerceros: "Intereses por préstamos a terceros (diferentes al sector financiero)",
    IntrumentosFinancierosMedidos: "Instrumentos financieros medidos a costo amortizado distinto a préstamos",
    InteresesImplicitos: "Intereses implícitos (transacciones de financiación)",
    DiferenciaCambio: "Diferencia en cambio",
    GananciasInversionesSubsidiariasAsociadasNegocios: "GananciasInversionesSubsidiariasAsociadasNegocios",
    GananciasMetodoParticipacion: "Ganancias por el método de participación",
    GananciasCambioValorRazonable: "Ganancias por cambio en el valor razonable",
    DividendosParticipacionesNoContribuyentes: "Dividendos y/o participaciones NO constitutivos de renta ni ganancia ocasional (incluye capitalizaciones no gravadas)",
    DividendosParticipacionesDistribuidosEntidadesNoColombia: "Dividendos o participaciones distribuidos por entidades no residentes en Colombia a una CHC y prima en colocación de acciones. ",
    DividendosParticipacionesGravadasTarifaGeneral: "Dividendos y/o participaciones gravadas a la tarifa general provenientes de sociedades y entidades extranjeras o de sociedades nacionales.",
    DividendosParticipacionesGravadasPersonaNatural: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2016 y anteriores)",
    DividendosParticipacionesGravadasPersonaNaturalSinResidencia: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2017 y siguientes) ",
    DividendosParticipaciones10: "Dividendos y/o participaciones gravadas al 10%",
    DividendosParticipacionesGravadasTarifaGeneralExtranjeras: "Dividendos y/o participaciones gravadas a tarifa general (EP y sociedades extranjeras - utilidades generadas a partir del año 2017) ",
    DividendosProyectosMegainversion: "Dividendos y participaciones provenientes de proyectos calificados como mega inversión gravadas al 27% ",
    IngresosPorMedicionesValorRazonable: "Ingresos por mediciones al valor razonable",
    ActivosBiologicos: "Activos biológicos",
    PropiedadesInversion: "Propiedades de inversión",
    InstrumentosFinancieros: "Instrumentos financieros, diferente a inversiones en subsidiarias, asociadas y/o negocios conjuntos ",
    InstrumentosDerivados: "Instrumentos derivados",
    UtilidadVentaEnajenacionActivosMenos2Anos: "Utilidad en la venta o enajenación de activos, bienes poseídos por menos de dos años",
    PropiedadesPlanta: "Propiedades, planta y equipo",
    ActivosNoCorrientesMantenidosVentaEntregarPropietarios: "Activos no corrientes mantenidos para la venta / entregar a propietarios",
    ActivosIntangibles: "Activos intangibles",
    InversionesAccionesOtrasParticipaciones: "Inversiones en acciones y otras participaciones",
    DisposicionOtrosInstrumentosFinancieros: "Disposición de otros instrumentos financieros",
    UtilidadVentaEnajenacionActivosMas2Anos: "Utilidad por venta o enajenación de activos, bienes poseídos por dos años o más (ganancia ocasional)",
    IngresosReversionDeterioroValor: "Ingresos por reversión de deterioro del valor",
    Inventarios: "Inventarios",
    PropiedadesPlantaEquipo: "Propiedades, planta y equipo",
    ActivosExploracionEvaluacionRecursosMinerales: "Activos de exploración y evaluación de recursos minerales",
    PropiedadesInversionMedidasCosto: "Propiedades de inversión medidas al costo",
    ActivosBiologicosMedidosCosto: "Activos biológicos medidos al modelo de costo",
    BienesArteCultura: "Bienes de arte y cultura",
    ActivosFinancieros: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)",
    CarteraCreditoOperacionesLeasing: "Cartera de crédito y operaciones de leasing",
    OtrasInversionesMedidasCostoMetodoParticipacion: "Otras inversiones medidas al costo o el método de la participación",
    OtrosDeterioros: "Otros deterioros",
    IngresosReversionProvisiones: "Ingresos por reversión de provisiones (pasivos de monto o fecha inciertos)",
    Garantias: "Garantías",
    ContratosOnerosos: "Contratos onerosos",
    Litigios: "Litigios",
    ReembolsosClientes: "Reembolsos a clientes",
    ReestructuracionesNegocios: "Reestructuraciones de negocios",
    PasivosContingentesCombinacionNegocios: "Pasivos contingentes asumidos en una combinación de negocios",
    IngresosReversionPasivosBeneficiosEmpleados: "Ingresos por reversión de pasivos por beneficios a los empleados",
    BeneficiosDeCortoPlazo: "Beneficios de corto plazo",
    BeneficiosDeLargoPlazo: "Beneficios de largo plazo",
    BeneficiosAEmpeladosPorTerminacionDelVinculoLaboral: "Beneficios a empleados por terminación del vínculo laboral",
    BeneficiosAEmpeladosPostEmpleo: "Beneficios a empleados post-empleo",
    TransferenciasSubvencionesAyudasGubernamentales: "Transferencias, subvenciones y ayudas gubernamentales",
    DonacionesAportacionesSimilares: "Donaciones, aportaciones y similares",
    ReembolsosCompaniasSegurosIndemnizaciones: "Reembolsos de compañías de seguros (indemnizaciones)",
    OtrasIndemnizaciones: "Otras indemnizaciones",
    OtrasReversionesRecuperaciones: "Otras reversiones o recuperaciones",
    GananciasNetasOperacionesDiscontinuas: "Ganancias netas en operaciones discontinuas",
    AjustesFiscales: "Ajustes fiscales",
    AdicionIngresos: "Adición de ingresos",
    RecuperacionDeDeduccionesSinIncidenciaContable: "Recuperación de deducciones sin incidencia contable",
    InteresesPresuntos: "Intereses presuntos",
    MayorIngresoPreciosDeTransferencia: "Mayor ingreso - Precios de Transferencia",
    OtrosIngresosFiscalesYNoIncluidosContablemente: "Otros ingresos fiscales y no incluidos contablemente",
    MenosIngresosNoConstitutivosRenta: "Menos: Ingresos no constitutivos de renta ni ganancia ocasional",
    TotalIngresos: "Total Ingresos",
    MateriasPrimasReventaBienes: "Materias primas, reventa de bienes terminados y servicios",
    CostossVentasCalculadoSistemaPermanente: "Costo de ventas calculado por el sistema permanente",
    MateriasPrimasProduccion: "Materias primas (para procesos de producción)",
    InventarioInicial: "Inventario inicial",
    ComprasLocales: "Compras locales",
    InventarioFinal: "Inventario final",
    CostoBienesVendidos: "Costos de los bienes vendidos (para comerciantes por reventa de bienes terminados)",
    ProductosProceso: "Productos en proceso",
    ProductosTerminados: "Producto terminado",
    CostosPrestacionServicios: "Costos en la prestación de servicios (para prestadores de servicios)",
    OtrosSistemasDeterminacionCostoVentas: "Otros sistema de determinación del costo de ventas",
    ManoObra: "Mano de obra",
    CortoPlazo: "Corto plazo",
    LargoPlazo: "Largo plazo",
    PostTerminacionVinculoLaboral: "Por terminación del vinculo laboral",
    PostEmpleo: "Post empleo",
    DepresionacionesAmortizacionesDeterioros: "Depreciaciones, amortizaciones y deterioros",
    DepreciacionPropiedadesPlantaEquipo: "Depreciación propiedades, planta y equipo",
    AjusteAcumunlado: "Del ajuste acumulado por revaluaciones o re expresiones",
    DepreciacionPropiedadesInversion: "Depreciación propiedades de inversión",
    DepreciacionActivosBiologicos: "Depreciación activos biológicos",
    AmortizacionActivosIntangibles: "Amortización activos intangibles",
    DepreciacionDerechosUsoArrendamientos: "Depreciación derechos de uso en arrendamientos operativos (NIIF 16)",
    OtrasDepreciacionesAmortizaciones: "Otras depreciaciones y amortizaciones",
    DeterioroValorActivos: "Deterioro del valor de los activos",
    OtrosCostos: "Otros costos",
    ServiciosTecnicos: "Servicios técnicos",
    VinculadosEconomicos: "Vinculados económicos",
    JurisdiccionesNoCooperantesBajaNulaImposicion: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    NoVinculados: "No vinculados",
    AsistenciaTecnica: "Asistencia técnica",
    OtrosConceptosReconocidosCostos: "Otros conceptos reconocidos como costo en el estado de resultados",
    OtrosConceptosFiscalesNoReconocidos: "Otros costos fiscales no reconocidos contablemente",
    MenosCostoAjustePrecios: "Menor costo ajuste precios de transferencia",
    TotalCostos: "Total Costos",
    OtrosGastosAdministracion: "Otros gastos de administración",
    ImpuestosDistintosAlImpuestosDeRentaYComplementarios: "Impuestos distintos a los impuestos de renta y complementarios",
    ContribucionesYAfiliaciones: "Contribuciones y afiliaciones",
    ServiciosAdministrativos: "Servicios administrativos",
    OtrosServicios: "Otros servicios",
    InvestigacionYDesarrollo: "Investigación y desarrollo",
    GastosLegales: "Gastos legales",
    ReparacionMantenimientoAdecuacionInstalaciones: "Reparación, mantenimiento y adecuación de instalaciones",
    OtrosGastos: "Otros gastos",
    DepreciacionesAmortizacionesDeterioros: "Depreciaciones, amortizaciones y deterioros",
    DepreciacionArrendamientosOperativos: "Depreciación Arrendamientos operativos (NIIF 16)",
    OtrasDepreciaciones: "Otras depreciaciones",
    OtrasAmortizaciones: "Otras amortizaciones",
    GastosDistribucionVentas: "Gastos de distribución y ventas",
    OtrosGastosDistribucionVentas: "Otros gastos de distribución y ventas",
    ConstitucionDeReservas: "Constitución de reservas (empresas aseguradoras)",
    LiquidacionSiniestros: "Liquidación de siniestros",
    PrimasReaseguros: "Primas de reaseguros",
    GastosFinancieros: "Gastos financieros",
    InteresesDevengadosSectorFinanciero: "Intereses devengados - sector financiero",
    InteresesDevengadosPrestamosTerceros: "Intereses devengados por préstamos a terceros (diferentes al sector financiero)",
    CostosTransaccion: "Costos de transacción (comisiones bancarias, tasas, entre otros)",
    ActualizacionProvisiones: "Actualización de provisiones reconocidas a valor presente",
    AccionesPreferenciales: "Intereses por acciones preferenciales",
    OtrosGastosFinancieros: "Otros gastos financieros reconocidos como gasto en el estado de resultados",
    PredidasPorInversionesSubsidiariasAsociadasNegocios: "Pérdidas por inversiones en subsidiarias, asociadas y negocios conjuntos",
    PerdidaMetodoParticipacion: "Pérdidas por el método de participación",
    PerdidaMetodoValorRazonable: "Pérdidas por cambio en el valor razonable",
    PerdidasPorMedicionesValorRazonable: "Pérdidas por mediciones a valor razonable",
    PerdidaVentaEnajenacionActivosFijos: "Pérdida en la venta o enajenación de activos fijos",
    ValoracionVentaInversionesFondoLiquidez: "Valoración y venta de inversiones fondo de liquidez y títulos participativos, entre otros",
    DisposicionInstrumentosFinancieros: "Disposición de instrumentos financieros",
    DescuentoOperacionesFactoring: "Descuento en operaciones de factoring",
    GastosPorProviciones: "Gastos por provisiones (pasivos de monto o fecha inciertos)",
    ContribucionesEducacionEmpleados: "Contribuciones a la educación de los empleados (art.107-2 del ET)",
    DeduccionesFiscalesNoReconocidas: "Deducciones fiscales no reconocidas contablemente",
    PerdidasNetasOperacionesDiscontinuas: "Pérdidas netas en operaciones discontinuadas",
    MenorGastoDeduccionPrecioTransferencia: "Menor gasto o deducción-ajuste precios de transferencia",
    GanaciaPerdidaAntesImpuestos: "GANANCIA O PÉRDIDA ANTES DE IMPUESTO A LA RENTA / RENTA LIQUIDA",
    InformativoClasificacionDiferencias: "Informativo-Casificación de diferencias",
    DiferenciasPermanentesDisminuyenRentaLiquida: "Diferencias permanentes que disminuyen la Renta Liquida (-)",
    IngresosNoConstitutivosRenta: "Ingresos no constitutivos de renta ni ganancia ocasional",
    DeduccionEspecialeesInversionesAdquisicion: "Deducción especiales por inversiones o en adquisición de activos (contrato de estabilidad jurídica)",
    InversionesInvestigacion: "Inversiones en investigación, desarrollo tecnológico e innovación",
    MayorValorConstoActivosFijos: "Mayor valor del costo de los activos fijos por reajustes fiscales o saneamientos año 1995",
    RecuperacionDeducciones: "Recuperación de deducciones (valor fiscal)",
    SalariosConDeduccionesEspeciales: "Salarios con deducciones especiales",
    ReintegroProvisionesDiferencias: "Reintegro o recuperación de provisiones que constituyan diferencias permanentes, en períodos anteriores – provisiones para gastos no deducibles",
    AjusteAtribucionRentas: "Ajuste por atribución de rentas establecimientos permanentes y sucursales",
    DiferenciasPermanentesAumentanRentaLiquida: "Diferencias permanentes que aumentan la Renta Liquida (+)",
    PerdidasGastosNoDeducibles: "Pérdidas y Gastos no deducibles",
    DeduccionesImpuestos: "Deducciones de impuestos (GMF, Patrimonio vehículos, entre otros)",
    GastosSinSoporte: "Gastos sin soporte",
    PagosExteriorSinRetencionFuente: "Pagos al exterior sin la prueba de la retención en la fuente",
    PagosExteriorExceden15PorcientoRentaLiquida: "Pagos al exterior que exceden el 15% de la renta líquida",
    DonacionesNoCumplenRequisitosLegales : "Donaciones que no cumplan los requisitos legales",
    SalariosSinPagoAportesParafiscales: "Salarios sin el pago de los aportes parafiscales",
    GastosVigenciasAnteriores: "Gastos de vigencias anteriores",
    GastoFinancieroNoDeducibleSubcapitalizacion: "Gasto financiero no deducible por regla de subcapitalización",
    OtrosGastosFinancierosNoDeducibles: "Otros gastos financieros no deducibles",
    DeterioroInversionesPerdidaEnajenacionAcciones: "Deterioro de inversiones para cubrir una pérdida en enajenación de acciones",
    PerdidaEnajenacionAccionesVentaInmuebles: "Pérdida en la enajenación de acciones y venta de bienes inmuebles",
    PerdidasNoDeduciblesFaltantesInventarios: "Pérdidas no deducibles por faltantes de inventarios",
    PerdidasMetodoParticipacion: "Perdidas por el método de participación",
    PagosRegaliasIntangiblesVinculadosExteriorZonasFrancas: "Pagos de regalías por concepto de intangibles a vinculados del exterior y zonas francas",
    LimitacionCostosComprasProveedoresFicticiosInsolventes: "Limitación de costos por compras a proveedores ficticios o insolventes",
    ImpuestosMultasSancionesInteresesMoratoriosCondenasNoDeducibles: "Impuestos, multas, sanciones, intereses moratorios y las condenas no deducibles",
    GastosNoRelacionCausalidadNecesidadActividadProductoraRenta: "Gastos que no guardan relación de causalidad y necesidad con la actividad productora de renta",
    MontoExcedeLimiteAtencionesClientesProveedoresEmpleados: "Monto que supera el limite permitido para atenciones a clientes, proveedores y empleados",
    ImportacionTecnologiaPatentesMarcas: "Importación de tecnología, patentes y marcas",
    GastosNoDeduciblesContratosArrendamientoPermanente: "Gastos no deducibles en contratos de arrendamientos, de naturaleza permanente",
    GastosNoDeduciblesOperacionesIVAConNoInscritosRegimenComun: "Gastos no deducibles por operaciones gravadas con IVA realizadas con personas no inscritas en el Régimen Común del Impuesto Sobre las Ventas",
    GastoNoDeducibleDonaciones: "Gasto no deducible por donaciones",
    GastosNoDeduciblesAtribuiblesIngresosExentosNoConstitutivosRenta: "Gastos no deducibles, atribuibles a ingresos exentos o no constitutivos de renta ni ganancia ocasional",
    OtrosGastosNoDeduciblesPermanente: "Otros gastos no deducibles de naturaleza permanente",
    OtrosAjustes: "Otros ajustes",
    DividendosDeclaradosContribuyentePeriodoFiscal: "Dividendos declarados a favor del contribuyente en el periodo fiscal",
    RentasLiquidasVentasInversiones: "Rentas liquidas por ventas de inversiones",
    MayorIngresoAjustesPreciosTransferencia: "Mayor ingreso, ajustes por precios de transferencia",
    MenorCostoDeduccionAjustesPreciosTransferencia: "Menor costo o deducción, ajustes por precios de transferencia",
    RentasLiquidasRecuperacionDeduccionesPermanente: "Rentas líquidas por recuperación de deducciones de naturaleza permanente",
    AjusteAtribucionRentasEstablecimientosPermanentesSucursales: "Ajuste por atribución de rentas establecimientos permanentes y sucursales",
    GananciaPerdidaContableDiferenciaPermanente: "GANANCIA (O PÉRDIDA) CONTABLE  CON DIFERENCIAS PERMANENTES",
    AjustesResultadoContableDiferenciasTemporales: "AJUSTES AL RESULTADO CONTABLE POR DIFERENCIAS TEMPORALES (que afectan el resultado)",
    DiferenciasTemporalesDeducibles: "Diferencias temporales deducibles",
    PerdidasDeterioroValorActivos: "Pérdidas por deterioro del valor de los activos",
    OtrasPerdidasDeterioros: "Otras pérdidas por deterioro",
    GastosDepreciacionExedidoLimiteFiscal: "Gastos por Depreciación que han excedido el límite máximo fiscal",
    GastosAmortizacionExedidoLimiteFiscal: "Gastos por amortización que han excedido el límite máximo fiscal",
    PerdidasMedicionValorRazonable: "Pérdidas por medición a Valor Razonable",
    OtrosInstrumentosFinancieros: "Otros instrumentos financieros, diferentes a títulos de renta fija, medidos al modelo del valor razonable",
    PerdidaDiferenciaCambio: "Pérdida por diferencia en cambio",
    PerdidasEsperadasContratosConstruccionProvisionesContratosOnerosos: "Pérdidas esperadas en contratos de construcción y otros servicios (provisiones por contratos onerosos)",
    InteresesImplicitosVentasPrestamosTerceros: "Intereses implícitos (ventas o préstamos concedidos a terceros)",
    OtrasProvisionesPasivosMontoFechaInciertos: "Otras Provisiones asociadas a pasivos de monto o fecha inciertos",
    BeneficiosEmpleados: "Por beneficios a empleados",
    GastosActualizacionProvisionesValorPresente: "Gastos por actualización de provisiones reconocidas a valor presente",
    CostosPrestamosActivosAptosNIIFParaPYMES: "Costos por préstamos atribuibles a activos aptos para entidades que aplican la NIIF para PYMES",
    PasivosIngresosDiferidosProgramasFidelizacionClientes: "Pasivos por ingresos diferidos producto de programas de fidelización de clientes que no han sido reversados contablemente pero que deben ser gravados fiscalmente",
    AjustesContratosConcesionConstruccionAdministracionOperacionMantenimiento: "Ajustes por contratos de concesión que incorporan las etapas de construcción, administración, operación y mantenimiento",
    GastosEstablecimiento: "Gastos de establecimiento",
    GastosInvestigacionDesarrolloInnovacion: "Gastos de investigación, desarrollo e innovación",
    PagosBasadosAcciones: "Por pagos basados en acciones",
    ExplotacionMinasPetroleoGas: "En la explotación de minas, petróleo y gas",
    RentasDerechoCobroNoCumplieronCriteriosIngresosPeriodoGravable: "Rentas con derecho a cobro (causadas) que no cumplieron criterios para ser contabilizadas como ingresos del período gravable",
    OtrasDiferenciasTemporalesDeducibles: "Otras diferencias temporales deducibles",
    DiferenciasTemporalesImponiblesGravables: "Diferencias temporales imponibles (gravables)",
    GastosDepreciacionesActivosFijosAceptadosTemporaria: "Gastos por depreciaciones de activos fijos no aceptadas fiscalmente de naturaleza temporaria",
    CostosAtribuidosFechaTransicion: "Costos atribuidos en la fecha de transición a los nuevos marcos técnicos normativos contables",
    ApliacionModeloRevaluacion: "Aplicación del modelo de revaluación",
    CostosEstimadosDesmantelamiento: "Costos estimados de desmantelamiento",
    GastosAmortizacionesActivosIntangiblesAceptadasFiscalmenteTemporaria: "Gastos por amortizaciones de activos intangibles no aceptadas fiscalmente de naturaleza temporaria",
    GananciasMedicionValorRazonable: "Ganancias por la medición a valor razonable",
    GananciaPorDiferenciaCambio: "Ganancia por diferencia en cambio",
    IngresosProvenientesContraprestacionVariable: "Ingresos provenientes por contraprestación variable",
    DeduccionEspecialImpuestoVentas: "Deducción especial del impuesto sobre las ventas",
    OtrasDiferencias: "Otras diferencias temporales imponibles (gravables)",
    OtrasDiferenciasTemporales: "Otras diferencias temporales",
    MedicionesActivosBiologicosValorRazonable: "Mediciones de activos biológicos al valor razonable menos costos de venta",
    CambiosValorRazonableMenosCostosVenta: "Cambios en el valor razonable menos costos de venta",
    CostosProduccionTransformacionBiologica: "Costos de producción atribuibles a la transformación biológica o pérdidas causadas en caso de destrucción, daños, muerte y otros eventos",
    DepreciacionFiscalAnimalesProductores: "Depreciación fiscal de animales productores",
    AjustesTitulosRentaFijaModeloValorRazonable: "Ajustes por títulos de renta fija (activos financieros) medidos al modelo del valor razonable",
    AjustesValorRazonable: "Ajustes por valor razonable",
    AjusteRendimientosFinancieros: "Ajuste por rendimientos financieros calculados de manera lineal para efectos fiscales",
    GastosAmortizacionFiscalAcelerada: "Gastos por amortización fiscal acelerada",
    AjustesOperacionReporteRepo: "Ajustes por operaciones de reporto o repo, simultáneas y de transferencia temporal de valores",
    ContratosArrendamientos: "Contratos de arrendamientos",
    RentaLiquidaOrdinariaEjercicio: "RENTA LIQUIDA ORDINARIA DEL EJERCICIO (Incluyendo dividendos y antes de las Rentas liquidas pasivas ECE)",
    PerdidaLiquidaOrdinariaEjercicio: "o Pérdida Líquida ordinaria del ejercicio (incluyendo dividendos y antes  de las rentas liquidas pasivas ECE)",
    AjustesParaLiquidacion: "AJUSTES PARA LIQUIDACIÓN",
    MenosValorInversionesRealizadas: "Menos: Valor inversiones realizadas en el periodo",
    MasValorInversionesLiquidas: "Más: Valor inversiones liquidadas en el periodo",
    RentasPasivasECE: "Rentas pasivas ECE",
    DividendosRetirosRepartos: "Dividendos, retiros y repartos",
    InteresesRendimientosFinancieros: "Intereses y rendimientos financieros",
    ProvenientesActivosIntangibles: "Provenientes de activos intangibles",
    EnajenacionCesionDerechos: "Enajenación o cesión de derechos",
    EnajenacionArrendamientoInmuebles: "Enajenación o arrendamiento de inmuebles",
    CompraVentaBienesCorporales: "Compra y venta de bienes corporales",
    PorServicios: "Por servicios",
    RentasLiquidasPasivasECE: "Rentas liquidas pasivas - ECE",
    RentaLiquidaRecuperaciónDeducciones: "Renta líquida por recuperación de deducciones",
    RentaLiquidaOrdinariaEjercicioExcedenteNEto: "RENTA LÍQUIDA ORDINARIA DEL EJERCICIO-EXCEDENTE NETO (incluye únicamente dividendos de sociedades nacionales a tarifa general)",
    PerdidaLiquidaEjercicio: "o, PÉRDIDA LÍQUIDA DEL EJERCICIO (incluye únicamente dividendos de sociedades nacionales a tarifa general)",
    PerdidasFiscales: "De pérdidas fiscales",
    ExcesoREntaPresuntivaRentaOrdinaria: "Del exceso de renta presuntiva sobre renta ordinaria",
    RentaLquidaDividendosSociedadesNacionales: "Renta líquida(incluye únicamente dividendos de sociedades nacionales a tarifa general)",
    RentaPresuntiva: "Renta presuntiva",
    PatrimoniLiquidoAñoPeriodoGravable: "Patrimonio líquido del año o período gravable anterior",
    ValorPatrimonialNeto: "Valor patrimonial neto",
    AccionesAportesPoseidosSociedadesNacionales: "Acciones y aportes poseídos en sociedades nacionales",
    BienesAfectadosHecosConstitutivos: "Bienes afectados por hechos constitutivos de fuerza mayor o caso fortuito",
    BienesVinculadosEmpresasPeriodoImproductivo: "Bienes vinculados a empresas en período improductivo",
    BienesDestinadosExclusivamenteActividadesDeportivas: "Bienes destinados exclusivamente a actividades deportivas",
    BienesVinculadosEmpresasExclusivamenteMineras: "Bienes vinculados a empresas exclusivamente mineras",
    Primeras19000UVTAgropecuario: "Primeras 19.000 UVT de activos destinados al sector agropecuario",
    OtrasExclusiones: "Otras exclusiones",
    BaseCalcykiRentaPresuntiva: "Base de cálculo de la renta presuntiva",
    CalculoRantaPresuntiva: "Cálculo Renta presuntiva (0% salvo excepciones)",
    RentaGravableGeneraActivosExcluidos: "Renta gravable generada por los activos excluidos",
    RenteExenta: "Renta exenta",
    RentasGrvablesREntaLiquida: "Rentas gravables (renta líquida)",
    PerdidasCompensadasModificadasLiquidacionOfical: "Pérdidas compensadas modificadas por Liquidación Oficial",
    PasivosInexistentes: "Pasivos inexistentes",
    OmisionActivos: "Omisión de activos",
    ComparacionPatrimonial: "Comparación patrimonial",
    ESALRTE: "ESAL (RTE)",
    ExedentesNoReinvertidos: "Excedentes no reinvertidos",
    AsignacionesPermanentes: "Asignaciones permanentes no ejecutadas",
    InversionesLiquidas: "Inversiones liquidadas y no reinvertidas",
    RentasLiquidasGravables: "Rentas liquidas gravables",
    ImpuestoSobreREntaLiquidaGravable: "Impuesto sobre la renta líquida gravable",
    GananciasOcasionalesGravables: "Ganancias ocasionales gravables",
    IngresosGananciaOcasionalVentaActivosFijos: "Ingresos por ganancia ocasional en venta de activos fijos",
    OtrosIngresosGananciaOcasional: "Otros ingresos por ganancia ocasional",
    TotalIngresosGananciasOcasionales: "Total Ingresos por ganancias ocasionales",
    CostosGananciaOcasionalVentaActivosFijos: "Costos por ganancia ocasional en venta de activos fijos",
    OtrosCostosGananciasOcasionales: "Otros costos por ganancias ocasionales",
    TotalCostosGananciasOcasionales: "Total costos por ganancias ocasionales",
    GananciasOcasionalesNoGravadasVentaAccionesECE: "Ganancias ocasionales no gravadas por la venta de acciones ECE",
    OtrasGananciasOcasionalesNoGravadasExentas: "Otras ganancias ocasionales no gravadas y exentas",
    RentasDeudoresRegimenLey11162006Decretos5607722020: "Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020",
    UtilizacionPerdidasFiscalesAcumuladasArt15Decreto7722020: "Utilización pérdidas fiscales acumuladas (Inc. 2, Art 15 Decreto 772 de 2020) ",
    ImpuestoGananciaOcasional: "Impuesto de ganancia ocasional",
    DescuentosTributarios: "Descuentos tributarios",
    DescuentosImpuestosPAgadosExteriorGananciasOcacionales: "Descuentos por impuestos pagados en el exterior por ganancias ocasionales",
    ValorInversionObras50ValorImpuestoCargo: "Valor inversión obras por impuestos hasta del 50% del valor del impuesto a cargo (Modalidad de pago 1)",
    DescuentoEfectivoInversionObrasImpuestos: "Descuento efectivo inversión obras por impuestos (Modalidad de pago 2)",
    AnticipoRentaLiquidadoAnioAnterior: "Anticipo renta liquidado año anterior",
    AnticipoSobretasaLiquidadpAnioAnterior: "Anticipo sobretasa liquidado año gravable anterior",
    SaldoFavorAnioGravableAnteriorSinSolicitusDevolucion: "Saldo a favor año gravable anterior sin solicitud de devolución o compensación",
    PorVentas: "Por ventas",
    PorRendimientos: "Por rendimientos",
    PorOtrosConceptos: "Por otros conceptos",
    OtrasReneciones: "Otras retenciones",
    PorHonorarios: "Por honorarios",
    PorDividendos: "Por dividendos",
    OtrasRetenciones: "Otras retenciones",
    TotalRetencionesAnioGravableDeclara: "Total retenciones año gravable que declara",
    AnticipoRentaAnioGravableSiguiente: "Anticipo renta por el año gravable siguiente",
    AnticipoSobretasaInstitucionesAnioGravableAnterior: "Anticipo sobretasa instituciones financieras año gravable anterior",
    SobretasaInstitucionesFinancieras: "Sobretasa instituciones financieras",
    AnticipoSobretasaIntitucionesFinancierasAnioGravableSiguiente: "Anticipo sobretasa instituciones financieras año gravable siguiente",
    CreditoFiscalInversionesEnProyectosInvestigacion: "Crédito fiscal para inversiones en proyectos de investigación, desarrollo tecnológico e innovación o vinculación de capital humano de alto nivel (art.256-1 del ET creado con art. 168 ley 1955 mayo de 2019)",
    InformativoOtroResultadoIntegral: "INFORMATIVO-OTRO RESULTADO INTEGRAL (ORI)",
    NoSeReclassificanAlResultado: "No se reclassifican al resultado",
    CambiosSuperavitRevaluacion: "Cambios en el superávit de revaluación",
    NuevasMedicionesPlanesBeneficiosDefinidos: "Nuevas mediciones de los planes de beneficios definidos",
    InversionesInstrumentosPatrimonio: "Inversiones en instrumentos de patrimonio",
    ParticipacionOtroResultadoIntegralAsociadasNegociosConjuntosMetodoParticipacion: "Participación otro resultado integral de asociadas y negocios conjuntos contabilizados utilizando el método de la participación",
    InstrumentosCoberturaInversionesInstrumentosPatrimonio: "Instrumentos de cobertura que cubren inversiones en instrumentos de patrimonio",
    CambioValorRazonablePasivosFinancierosRiesgoCreditoPasivo: "Cambio valor razonable de pasivos financieros atribuible a cambios en el riesgo de crédito del pasivo",
    SeReclassificanAlResultado: "Se reclassifican al resultado",
    DiferenciasCambioConversion: "Diferencias de cambio por conversión",
    ActivosFinancierosDisponiblesVenta: "Activos financieros disponibles para la venta",
    ActivosFinancierosValorRazonableCambiosORI: "Activos financieros medidos al valor razonable con cambios en el ORI",
    CoberturaFlujosEfectivo: "Cobertura de flujos de efectivo",
    CoberturasInversionesNetasNegociosExtranjero: "Coberturas de inversiones netas en negocios en el extranjero",
    OtrasPartidasReconocidasORI: "Otras partidas que deban ser reconocidas en el ORI",
    OtrpResultadoIntegralAntesImpuestos: "OTRO RESULTADO INTEGRAL ANTES DE IMPUESTOS",
    ResultadoIntegralTotalAnio: "RESULTADO INTEGRAL TOTAL DEL AÑO",
    GastoIngresoImpuestoRentaComplementarioPeriodo: "Gasto / ingreso impuesto de renta y complementario del período",
    GastosImpuestoCorriente: "Gastos por impuesto corriente",
    SobreRentaLiquidaPresuntivaPeriodo: "Sobre renta liquida / presuntiva del período",
    GastoAjustesPeriodosAnteriores: "Gasto por ajustes respecto a periodos anteriores",
    IngresosAjustesPeriodosAnteriores: "Ingreso por ajustes respecto a periodos anteriores",
    ImpuestosAsumidosExteriorConveniosTratados: "Impuestos asumidos del exterior-convenios o tratados",
    GastoImpuestoDiferido: "Gasto por impuesto diferido",
    IngresoImpuestoDiferido: "Ingreso impuesto diferido",
    ValorNetoGastoImpuesto: "Valor neto gasto por impuesto",
    DatosInformativoConcepto: "DATOS INFORMATIVOS-CONCEPTO",
    IngresosDevengadosFidelizacionClientes: "Ingresos devengados (contables) por fidelización de clientes",
    IngresosFiscalesFidelizacionClientesSinDevengoContable: "Ingresos fiscales por fidelización de clientes, sin devengo contable",
    RetirosConsumoPublicidadPropagandaPromocion: "Retiros para consumo y publicidad, propaganda y promoción",
    DividendosDecretadosPeriodoGravable: "Dividendos decretados en el periodo gravable",
    DividendosCobradosPeriodoGravable: "Dividendos cobrados en el periodo gravable",
    IngresosDevengadosFideicomisosEncargosFiduciariosFideicomitenteFiduciante: "Ingresos devengados de fideicomisos o encargos fiduciarios, calidad de fideicomitente o fiduciante",
    IngresosDevengadosFideicomisosEncargosFiduciariosBeneficiario: "Ingresos devengados de fideicomisos o encargos fiduciarios, calidad de beneficiario",
    CostosGastos: "COSTOS Y GASTOS",
    CostosGastosDevengadosFidelizacionClientes: "Costos y gastos devengados, asociados a ingresos por fidelización de clientes",
    BajasInventariosReconocidosCostoGastoEstadoResultados: "Bajas de inventarios (faltantes, caso fortuito o fuerza mayor), reconocidos como costo o gasto en el estado de resultados del ejercicio",
    CostosIndirectosProduccionNoDistribuidosCostoInventario: "Costos indirectos de producción no distribuidos como costo del inventario, reconocidos como costo o gasto en el estado de resultados del ejercicio",
    MontoDescuentosObtenidosPeriodoCompraInventarios: "Monto descuentos obtenidos en el periodo en la compra de inventarios",
    CostosGastosDevengadosFideicomisosEncargosFiduciariosFideicomitenteFiduciante: "Costos y gastos devengados de fideicomisos o encargos fiduciarios, calidad de fideicomitente o fiduciante",
    CostosGastosDevengadosFideicomisosEncargosFiduciariosBeneficiario: "Costos y gastos devengados de fideicomisos o encargos fiduciarios, calidad de beneficiario",
    CostosDeduccionesNoProcedentesActividadMeritoriaRegimenTributarioEspecial: "Costos y deducciones no procedentes-actividad meritoria (Régimen tributario especial)",
    OtrosDatosInformativos: "OTROS DATOS INFORMATIVOS",
    TotalCostosGastosNomina: "Total costos y gastos por nómina",
    AportesSistemaSeguridadSocial: "Aportes al sistema de seguridad social",
    AportesSENAICBFCompensacion: "Aportes al SENA, ICBF, cajas de compensación",
    AportesEmpleadorSegurosPrivadosPensionesFondosPensionesVoluntarias: "Aportes del empleador a los seguros privados de pensiones y a los fondos de pensiones voluntarias",
    OperacionesVinculadosEconomicos: "Operaciones con vinculados económicos",
    CostosDeducciones: "Costos y deducciones",
    CompraInventarios: "Compra de inventarios",
    CompraActivosFijos: "Compra de activos fijos",
    ValorContable: "Valor contable",
    EfectoConversion: "Efecto de la conversión",
    MenorValorFiscal: "Menor valor fiscal",
    MayorValorFiscal: "Mayor valor fiscal",
    ValorFiscal: "Valor fiscal",
    Tarifa9: "Tarifa del 9%",
    Tarifa15: "Tarifa del 15%",
    Tarifa20: "Tarifa del 20%",
    MegaInversiones: "Mega inversiones",
    MegaInversiones27: "Mega inversiones 27%",
    TarifaGeneral240: "Tarifa general del 240 ET",
    ValorFiscalTieneDerecho: "Valor fiscal al que tiene derecho",
    ValorFiscalSolicitado: "Valor fiscal solicitado",
    Generaciones: "Generaciones (+)",
    Reversiones: "Reversiones (-)",
    GeneracionesDeducibles: "Generaciones deducibles",
    GeneracionesImponibles: "Generaciones imponibles",
    ReversionesDeducibles: "Reversiones deducibles",
    ReversionesImponibles: "Reversiones imponibles",
}
