export const calculateValorFiscalInputs = [
    "Ingresos",
    "Costos",
    "Gastos",
]

export const excludedCalculateValorFiscalInputs = [
    "MenorGastoDeduccionPrecioTransferencia",
    "GananciasMetodoParticipacion",
    "GananciasCambioValorRazonable",
    "GananciasNetasOperacionesDiscontinuas",
]

export const noInputsValues = [
    "ValorFiscal",
    "Total",
    "Otras",
    "TotalCostos",
    "TotalIngresos",
    "TotalGastos",
];

export const rentaLiquidaNames = {
    Ingresos: "Ingresos",
    IngresosNetosActividadIndustrialCoSer: "Ingresos netos Actividad Industrial, comercial y servicios",
    VentaTerritorioNacional: "Venta en territorio nacional",
    VentaExportacion: "Venta en exportación a otros países",
    VentaZonaFranca: "Venta en zona franca",
    VentaComercializadorasInternacionales: "Venta a comercializadoras internacionales",
    VentaJurisdiccionesNoCooperantes: "venta jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    VentaVinculadoEconomicosFranca: "Venta vinculado Económicos zona Franca y exterior",
    PrestacionServiciosTerritorioNacional: "Prestación de servicios al territorio nacional",
    PrestacionServiciosExportacion: "Prestación de servicios en exportación a otros países",
    PrestacionServiciosZonaFranca: "Prestación de servicios en zona franca",
    PrestacionServiciosComercializadorasInternacionales: "Prestación de servicios a comercializadoras internacionales",
    PrestacionServiciosJurisdiccionesNoCooperantes: "Prestación de servicios a jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    PrestacionServiciosVinculadoEconomicosFranca: "Prestación de servicios a vinculado Económicos zona Franca y exterior",
    ServiciosConstruccion: "Servicios de construcción",
    AcuerdosConcesion: "Acuerdos de concesión de servicios",
    ArrendamientosOperativos: "Arrendamientos operativos",
    Regalias: "Regalías",
    Comisiones: "Comisiones (relaciones de agencia)",
    HonorariosProfesionales: "Honorarios profesionales",
    ActividadesSegurosCapitalizacion: "Actividades de seguros y capitalización",
    LiberacionReservasContratosSeguros: "Liberación de reservas en contratos de seguros",
    ComisionesBancarias: "Comisiones bancarias, costos de transacción enre otros",
    OtrosIngresos: "Otros ingresos",
    DevolucionesRebajasDescuentos: "Devoluciones, rebajas y descuentos",
    VentaBienes: "Venta de bienes",
    PrestacionServicios: "Prestación de servicios",
    OtrasDevoluciones: "Otras devoluciones",
    IngresosFinancieros: "Ingresos financieros",
    ArrendamientoFinanciero: "Arrendamiento financiero o mercantil (leasing)",
    InteresesSectorFinanciero: "Intereses - sector financiero",
    InteresesPrestamosTerceros: "Intereses por préstamos a terceros (diferentes al sector financiero)",
    IntrumentosFinancierosMedidos: "Instrumentos financieros medidos a costo amortizado distinto a préstamos",
    InteresesImplicitos: "Intereses implícitos (transacciones de financiación)",
    DiferenciaCambio: "Diferencia en cambio",
    GananciasInversionesSubsidiariasAsociadasNegocios: "GananciasInversionesSubsidiariasAsociadasNegocios",
    GananciasMetodoParticipacion: "Ganancias por el método de participación",
    GananciasCambioValorRazonable: "Ganancias por cambio en el valor razonable",
    DividendosParticipacionesNoContribuyentes: "Dividendos y/o participaciones NO constitutivos de renta ni ganancia ocasional (incluye capitalizaciones no gravadas)",
    DividendosParticipacionesDistribuidosEntidadesNoColombia: "Dividendos o participaciones distribuidos por entidades no residentes en Colombia a una CHC y prima en colocación de acciones. ",
    DividendosParticipacionesGravadasTarifaGeneral: "Dividendos y/o participaciones gravadas a la tarifa general provenientes de sociedades y entidades extranjeras o de sociedades nacionales.",
    DividendosParticipacionesGravadasPersonaNatural: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2016 y anteriores)",
    DividendosParticipacionesGravadasPersonaNaturalSinResidencia: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2017 y siguientes) ",
    DividendosParticipaciones10: "Dividendos y/o participaciones gravadas al 10%",
    DividendosParticipacionesGravadasTarifaGeneralExtranjeras: "Dividendos y/o participaciones gravadas a tarifa general (EP y sociedades extranjeras - utilidades generadas a partir del año 2017) ",
    DividendosProyectosMegainversion: "Dividendos y participaciones provenientes de proyectos calificados como mega inversión gravadas al 27% ",
    IngresosPorMedicionesValorRazonable: "Ingresos por mediciones al valor razonable",
    ActivosBiologicos: "Activos biológicos",
    PropiedadesInversion: "Propiedades de inversión",
    InstrumentosFinancieros: "Instrumentos financieros, diferente a inversiones en subsidiarias, asociadas y/o negocios conjuntos ",
    InstrumentosDerivados: "Instrumentos derivados",
    UtilidadVentaEnajenacionActivosMenos2Anos: "Utilidad en la venta o enajenación de activos, bienes poseídos por menos de dos años",
    PropiedadesPlanta: "Propiedades, planta y equipo",
    ActivosNoCorrientesMantenidosVentaEntregarPropietarios: "Activos no corrientes mantenidos para la venta / entregar a propietarios",
    ActivosIntangibles: "Activos intangibles",
    InversionesAccionesOtrasParticipaciones: "Inversiones en acciones y otras participaciones",
    DisposicionOtrosInstrumentosFinancieros: "Disposición de otros instrumentos financieros",
    UtilidadVentaEnajenacionActivosMas2Anos: "Utilidad por venta o enajenación de activos, bienes poseídos por dos años o más (ganancia ocasional)",
    IngresosReversionDeterioroValor: "Ingresos por reversión de deterioro del valor",
    Inventarios: "Inventarios",
    PropiedadesPlantaEquipo: "Propiedades, planta y equipo",
    ActivosExploracionEvaluacionRecursosMinerales: "Activos de exploración y evaluación de recursos minerales",
    PropiedadesInversionMedidasCosto: "Propiedades de inversión medidas al costo",
    ActivosBiologicosMedidosCosto: "Activos biológicos medidos al modelo de costo",
    BienesArteCultura: "Bienes de arte y cultura",
    ActivosFinancieros: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)",
    CarteraCreditoOperacionesLeasing: "Cartera de crédito y operaciones de leasing",
    OtrasInversionesMedidasCostoMetodoParticipacion: "Otras inversiones medidas al costo o el método de la participación",
    OtrosDeterioros: "Otros deterioros",
    IngresosReversionProvisiones: "Ingresos por reversión de provisiones (pasivos de monto o fecha inciertos)",
    Garantias: "Garantías",
    ContratosOnerosos: "Contratos onerosos",
    Litigios: "Litigios",
    ReembolsosClientes: "Reembolsos a clientes",
    ReestructuracionesNegocios: "Reestructuraciones de negocios",
    PasivosContingentesCombinacionNegocios: "Pasivos contingentes asumidos en una combinación de negocios",
    IngresosReversionPasivosBeneficiosEmpleados: "Ingresos por reversión de pasivos por beneficios a los empleados",
    BeneficiosDeCortoPlazo: "Beneficios de corto plazo",
    BeneficiosDeLargoPlazo: "Beneficios de largo plazo",
    BeneficiosAEmpeladosPorTerminacionDelVinculoLaboral: "Beneficios a empleados por terminación del vínculo laboral",
    BeneficiosAEmpeladosPostEmpleo: "Beneficios a empleados post-empleo",
    TransferenciasSubvencionesAyudasGubernamentales: "Transferencias, subvenciones y ayudas gubernamentales",
    DonacionesAportacionesSimilares: "Donaciones, aportaciones y similares",
    ReembolsosCompaniasSegurosIndemnizaciones: "Reembolsos de compañías de seguros (indemnizaciones)",
    OtrasIndemnizaciones: "Otras indemnizaciones",
    OtrasReversionesRecuperaciones: "Otras reversiones o recuperaciones",
    GananciasNetasOperacionesDiscontinuas: "Ganancias netas en operaciones discontinuas",
    AjustesFiscales: "Ajustes fiscales",
    AdicionIngresos: "Adición de ingresos",
    RecuperacionDeDeduccionesSinIncidenciaContable: "Recuperación de deducciones sin incidencia contable",
    InteresesPresuntos: "Intereses presuntos",
    MayorIngresoPreciosDeTransferencia: "Mayor ingreso - Precios de Transferencia",
    OtrosIngresosFiscalesYNoIncluidosContablemente: "Otros ingresos fiscales y no incluidos contablemente",
    MenosIngresosNoConstitutivosRenta: "Menos: Ingresos no constitutivos de renta ni ganancia ocasional",
    TotalIngresos: "Total Ingresos",
    MateriasPrimasReventaBienes: "Materias primas, reventa de bienes terminados y servicios",
    CostossVentasCalculadoSistemaPermanente: "Costo de ventas calculado por el sistema permanente",
    MateriasPrimasProduccion: "Materias primas (para procesos de producción)",
    InventarioInicial: "Inventario inicial",
    ComprasLocales: "Compras locales",
    InventarioFinal: "Inventario final",
    CostoBienesVendidos: "Costos de los bienes vendidos (para comerciantes por reventa de bienes terminados)",
    ProductosProceso: "Productos en proceso",
    ProductosTerminados: "Producto terminado",
    CostosPrestacionServicios: "Costos en la prestación de servicios (para prestadores de servicios)",
    OtrosSistemasDeterminacionCostoVentas: "Otros sistema de determinación del costo de ventas",
    ManoObra: "Mano de obra",
    CortoPlazo: "Corto plazo",
    LargoPlazo: "Largo plazo",
    PostTerminacionVinculoLaboral: "Por terminación del vinculo laboral",
    PostEmpleo: "Post empleo",
    DepresionacionesAmortizacionesDeterioros: "Depreciaciones, amortizaciones y deterioros",
    DepreciacionPropiedadesPlantaEquipo: "Depreciación propiedades, planta y equipo",
    AjusteAcumunlado: "Del ajuste acumulado por revaluaciones o re expresiones",
    DepreciacionPropiedadesInversion: "Depreciación propiedades de inversión",
    DepreciacionActivosBiologicos: "Depreciación activos biológicos",
    AmortizacionActivosIntangibles: "Amortización activos intangibles",
    DepreciacionDerechosUsoArrendamientos: "Depreciación derechos de uso en arrendamientos operativos (NIIF 16)",
    OtrasDepreciacionesAmortizaciones: "Otras depreciaciones y amortizaciones",
    DeterioroValorActivos: "Deterioro del valor de los activos",
    OtrosCostos: "Otros costos",
    ServiciosTecnicos: "Servicios técnicos",
    VinculadosEconomicos: "Vinculados económicos",
    JurisdiccionesNoCooperantesBajaNulaImposicion: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales",
    NoVinculados: "No vinculados",
    AsistenciaTecnica: "Asistencia técnica",
    OtrosConceptosReconocidosCostos: "Otros conceptos reconocidos como costo en el estado de resultados",
    OtrosConceptosFiscalesNoReconocidos: "Otros costos fiscales no reconocidos contablemente",
    MenosCostoAjustePrecios: "Menor costo ajuste precios de transferencia",
    TotalCostos: "Total Costos",
    OtrosGastosAdministracion: "Otros gastos de administración",
    ImpuestosDistintosAlImpuestosDeRentaYComplementarios: "Impuestos distintos a los impuestos de renta y complementarios",
    ContribucionesYAfiliaciones: "Contribuciones y afiliaciones",
    ServiciosAdministrativos: "Servicios administrativos",
    OtrosServicios: "Otros servicios",
    InvestigacionYDesarrollo: "Investigación y desarrollo",
    GastosLegales: "Gastos legales",
    ReparacionMantenimientoAdecuacionInstalaciones: "Reparación, mantenimiento y adecuación de instalaciones",
    OtrosGastos: "Otros gastos",
    DepreciacionesAmortizacionesDeterioros: "Depreciaciones, amortizaciones y deterioros",
    DepreciacionArrendamientosOperativos: "Depreciación Arrendamientos operativos (NIIF 16)",
    OtrasDepreciaciones: "Otras depreciaciones",
    OtrasAmortizaciones: "Otras amortizaciones",
    GastosDistribucionVentas: "Gastos de distribución y ventas",
    OtrosGastosDistribucionVentas: "Otros gastos de distribución y ventas",
    ConstitucionDeReservas: "Constitución de reservas (empresas aseguradoras)",
    LiquidacionSiniestros: "Liquidación de siniestros",
    PrimasReaseguros: "Primas de reaseguros",
    GastosFinancieros: "Gastos financieros",
    InteresesDevengadosSectorFinanciero: "Intereses devengados - sector financiero",
    InteresesDevengadosPrestamosTerceros: "Intereses devengados por préstamos a terceros (diferentes al sector financiero)",
    CostosTransaccion: "Costos de transacción (comisiones bancarias, tasas, entre otros)",
    ActualizacionProvisiones: "Actualización de provisiones reconocidas a valor presente",
    AccionesPreferenciales: "Intereses por acciones preferenciales",
    OtrosGastosFinancieros: "Otros gastos financieros reconocidos como gasto en el estado de resultados",
    PredidasPorInversionesSubsidiariasAsociadasNegocios: "Pérdidas por inversiones en subsidiarias, asociadas y negocios conjuntos",
    PerdidaMetodoParticipacion: "Pérdidas por el método de participación",
    PerdidaMetodoValorRazonable: "Pérdidas por cambio en el valor razonable",
    PerdidasPorMedicionesValorRazonable: "Pérdidas por mediciones a valor razonable",
    PerdidaVentaEnajenacionActivosFijos: "Pérdida en la venta o enajenación de activos fijos",
    ValoracionVentaInversionesFondoLiquidez: "Valoración y venta de inversiones fondo de liquidez y títulos participativos, entre otros",
    DisposicionInstrumentosFinancieros: "Disposición de instrumentos financieros",
    DescuentoOperacionesFactoring: "Descuento en operaciones de factoring",
    GastosPorProviciones: "Gastos por provisiones (pasivos de monto o fecha inciertos)",
    ContribucionesEducacionEmpleados: "Contribuciones a la educación de los empleados (art.107-2 del ET)",
    DeduccionesFiscalesNoReconocidas: "Deducciones fiscales no reconocidas contablemente",
    PerdidasNetasOperacionesDiscontinuas: "Pérdidas netas en operaciones discontinuadas",
    MenorGastoDeduccionPrecioTransferencia: "Menor gasto o deducción-ajuste precios de transferencia",
    GanaciaPerdidaAntesImpuestos: "GANANCIA O PÉRDIDA ANTES DE IMPUESTO A LA RENTA / RENTA LIQUIDA",
    InformativoClasificacionDiferencias: "Informativo-Casificación de diferencias",
    DiferenciasPermanentesDisminuyenRentaLiquida: "Diferencias permanentes que disminuyen la Renta Liquida (-)",
    IngresosNoConstitutivosRenta: "Ingresos no constitutivos de renta ni ganancia ocasional",
    DeduccionEspecialeesInversionesAdquisicion: "Deducción especiales por inversiones o en adquisición de activos (contrato de estabilidad jurídica)",
    /**
     * TODO: linea 4670 del json y 352 del excel
     */
}
